// components/organization-client.tsx
"use client";

import { useActionState, useState } from "react";
import {
  Building2,
  CreditCard,
  Plus,
  Trash2,
  AlertTriangle,
  Check,
  RotateCcw,
} from "lucide-react";
import type { Locale } from "@/lib/i18n/config";
import type { OrgPlanTier } from "@/types";
import {
  AMRAP_PLANS,
  ORG_DELETION_RETENTION_DAYS,
  canCreateGym,
  maxGyms,
} from "@/lib/plans/limits";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { LIMITS } from "@/lib/validation/schemas";
import {
  requestSubscriptionCheckout,
  requestCreateGym,
  scheduleGymDeletion,
  cancelGymDeletion,
  scheduleOrganizationDeletion,
  type OrgActionState,
} from "@/app/[locale]/(app)/organization/actions";

export type OrgGymRow = {
  id: string;
  name: string;
  deleted_at: string | null;
  isCurrent: boolean;
};

export type OrganizationLabels = {
  title: string;
  subtitle: string;
  currentPlan: string;
  subscriptionTitle: string;
  gymsTitle: string;
  gymsHint: string;
  addGym: string;
  addGymTitle: string;
  addGymDescription: string;
  gymName: string;
  currentGym: string;
  scheduledDeletion: string;
  cancelDeletion: string;
  deleteGym: string;
  deleteGymTitle: string;
  deleteGymHint: string;
  deleteOrg: string;
  deleteOrgTitle: string;
  deleteOrgHint: string;
  dangerTitle: string;
  dangerHint: string;
  confirmName: string;
  confirmNamePlaceholder: string;
  confirmDelete: string;
  cancel: string;
  close: string;
  save: string;
  upgrade: string;
  contactSales: string;
  current: string;
  checkoutComingSoon: string;
  contactProPlan: string;
  createGymComingSoon: string;
  gymCapContact: string;
  retentionNote: string;
  planFreemium: string;
  planStarter: string;
  planGrowth: string;
  planPro: string;
  priceFree: string;
  pricePerOrg: string;
  pricePerGym: string;
  priceContact: string;
  perMonth: string;
  gymQuota: string;
};

type Props = {
  locale: Locale;
  organizationName: string;
  planTier: OrgPlanTier;
  gyms: OrgGymRow[];
  labels: OrganizationLabels;
};

function planLabel(tier: OrgPlanTier, labels: OrganizationLabels) {
  switch (tier) {
    case "STARTER":
      return labels.planStarter;
    case "GROWTH":
      return labels.planGrowth;
    case "PRO":
      return labels.planPro;
    default:
      return labels.planFreemium;
  }
}

function priceLine(
  tier: OrgPlanTier,
  labels: OrganizationLabels,
): { amount: string; note: string } {
  const plan = AMRAP_PLANS.find((p) => p.tier === tier)!;
  if (plan.priceNote === "free") {
    return { amount: labels.priceFree, note: labels.perMonth };
  }
  if (plan.priceNote === "contact") {
    return { amount: labels.priceContact, note: labels.contactSales };
  }
  const amount = `$${plan.priceMxnMonthly}`;
  const note =
    plan.priceNote === "per_org"
      ? `${labels.perMonth} · ${labels.pricePerOrg}`
      : `${labels.perMonth} · ${labels.pricePerGym}`;
  return { amount, note };
}

function retentionDate(iso: string, locale: Locale) {
  const base = new Date(iso);
  base.setDate(base.getDate() + ORG_DELETION_RETENTION_DAYS);
  try {
    return base.toLocaleDateString(locale, {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  } catch {
    return base.toISOString().slice(0, 10);
  }
}

function Flash({ state }: { state: OrgActionState }) {
  if (!state?.message && !state?.error) return null;
  return (
    <p
      className={`rounded-lg border px-4 py-3 text-sm font-medium ${state.error
        ? "border-[var(--color-danger)]/25 bg-[var(--color-danger)]/10 text-[var(--color-danger)]"
        : "border-[var(--color-success)]/25 bg-[var(--color-success)]/10 text-[var(--color-success)]"
        }`}
      role="status"
    >
      {state.error ?? state.message}
    </p>
  );
}

export function OrganizationClient({
  locale,
  organizationName,
  planTier,
  gyms,
  labels,
}: Props) {
  const [createOpen, setCreateOpen] = useState(false);
  const [deleteGym, setDeleteGym] = useState<OrgGymRow | null>(null);
  const [deleteOrgOpen, setDeleteOrgOpen] = useState(false);

  const [checkoutState, checkoutAction, checkoutPending] = useActionState(
    requestSubscriptionCheckout,
    null as OrgActionState,
  );
  const [createState, createAction, createPending] = useActionState(
    requestCreateGym,
    null as OrgActionState,
  );
  const [gymDeleteState, gymDeleteAction, gymDeletePending] = useActionState(
    scheduleGymDeletion,
    null as OrgActionState,
  );
  const [gymCancelState, gymCancelAction, gymCancelPending] = useActionState(
    cancelGymDeletion,
    null as OrgActionState,
  );
  const [orgDeleteState, orgDeleteAction, orgDeletePending] = useActionState(
    scheduleOrganizationDeletion,
    null as OrgActionState,
  );

  const activeGymCount = gyms.filter((g) => !g.deleted_at).length;
  const gymCap = maxGyms(planTier);
  const canAddGym = canCreateGym(planTier, activeGymCount);
  const needsUpgradeForGym = !canAddGym;

  const [prevCreate, setPrevCreate] = useState(createState);
  if (createState !== prevCreate) {
    setPrevCreate(createState);
    if (createState?.success) setCreateOpen(false);
  }

  const [prevGymDelete, setPrevGymDelete] = useState(gymDeleteState);
  if (gymDeleteState !== prevGymDelete) {
    setPrevGymDelete(gymDeleteState);
    if (gymDeleteState?.success) setDeleteGym(null);
  }

  return (
    <div className="flex flex-col gap-5">
      <header>
        <h1 className="font-title text-3xl font-bold tracking-tight text-[var(--color-text)]">
          {labels.title}
        </h1>
        <p className="mt-1 text-sm text-[var(--color-muted)]">
          {labels.subtitle}
        </p>
        <p className="mt-3 inline-flex items-center gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm font-semibold text-[var(--color-text)] shadow-sm">
          <Building2 className="h-4 w-4 text-[var(--color-primary)]" aria-hidden />
          {organizationName}
          <span className="rounded-md bg-[var(--color-primary)]/15 px-2 py-0.5 text-xs font-bold text-[var(--color-primary)]">
            {planLabel(planTier, labels)}
          </span>
        </p>
      </header>

      <Flash state={checkoutState} />
      <Flash state={createState} />
      <Flash state={gymDeleteState} />
      <Flash state={gymCancelState} />
      <Flash state={orgDeleteState} />

      <section
        id="subscription"
        className="scroll-mt-6 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 shadow-sm sm:p-6"
      >
        <div className="mb-5 flex items-start gap-3">
          <div className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[var(--color-primary)]/15 text-[var(--color-primary)]">
            <CreditCard className="h-5 w-5" aria-hidden />
          </div>
          <div>
            <h2 className="font-title text-xl font-bold text-[var(--color-text)]">
              {labels.subscriptionTitle}
            </h2>
            <p className="mt-2 text-sm text-[var(--color-text)]">
              {labels.currentPlan}:{" "}
              <span className="font-semibold">{planLabel(planTier, labels)}</span>
            </p>
          </div>
        </div>

        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          {AMRAP_PLANS.map((plan) => {
            const isCurrent = plan.tier === planTier;
            const pricing = priceLine(plan.tier, labels);
            return (
              <article
                key={plan.tier}
                className={`flex flex-col rounded-xl border p-4 ${isCurrent
                  ? "border-[var(--color-primary)] bg-[var(--color-primary)]/5"
                  : "border-[var(--color-border)]"
                  }`}
              >
                <div className="flex items-center justify-between gap-2">
                  <h3 className="font-title text-base font-bold text-[var(--color-text)]">
                    {planLabel(plan.tier, labels)}
                  </h3>
                  {isCurrent ? (
                    <span className="inline-flex items-center gap-1 rounded-full bg-[var(--color-success)]/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-[var(--color-success)]">
                      <Check className="h-3 w-3" aria-hidden />
                      {labels.current}
                    </span>
                  ) : null}
                </div>
                <p className="mt-3 font-title text-2xl font-bold text-[var(--color-text)]">
                  {pricing.amount}
                </p>
                <p className="text-xs text-[var(--color-muted)]">{pricing.note}</p>
                {plan.tier !== "FREEMIUM" && !isCurrent ? (
                  plan.priceNote === "contact" ? (
                    <a
                      href="mailto:hello@amrap.space?subject=AMRAP%20Pro"
                      className="mt-auto pt-4"
                    >
                      <Button
                        type="button"
                        variant="primary"
                        className="mt-0 w-full shadow-sm"
                      >
                        {labels.contactSales}
                      </Button>
                    </a>
                  ) : (
                    <form action={checkoutAction} className="mt-auto pt-4">
                      <input type="hidden" name="locale" value={locale} />
                      <input type="hidden" name="tier" value={plan.tier} />
                      <Button
                        type="submit"
                        variant="primary"
                        className="mt-0 w-full shadow-sm"
                        disabled={checkoutPending}
                      >
                        {labels.upgrade}
                      </Button>
                    </form>
                  )
                ) : (
                  <div className="mt-auto pt-4" />
                )}
              </article>
            );
          })}
        </div>
      </section>

      <section
        id="gyms"
        className="scroll-mt-6 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 shadow-sm sm:p-6"
      >
        <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h2 className="font-title text-xl font-bold text-[var(--color-text)]">
              {labels.gymsTitle}
            </h2>
            <p className="mt-1 text-sm text-[var(--color-muted)]">
              {labels.gymsHint}
            </p>
            {gymCap != null ? (
              <p className="mt-2 text-xs font-medium text-[var(--color-muted)]">
                {labels.gymQuota
                  .replace("{used}", String(activeGymCount))
                  .replace("{max}", String(gymCap))}
              </p>
            ) : null}
            {needsUpgradeForGym ? (
              <p className="mt-2 text-sm text-[var(--color-muted)]">
                {labels.gymCapContact}
              </p>
            ) : null}
          </div>
          {!needsUpgradeForGym && (
            <Button
              type="button"
              variant="primary"
              className="mt-0 inline-flex shrink-0 items-center gap-1.5 shadow-sm"
              onClick={() => setCreateOpen(true)}
            >
              <Plus className="h-4 w-4" aria-hidden />
              {labels.addGym}
            </Button>
          )}
        </div>

        <ul className="divide-y divide-[var(--color-border)] rounded-xl border border-[var(--color-border)]">
          {gyms.map((gym) => (
            <li
              key={gym.id}
              className="flex flex-col gap-3 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"
            >
              <div className="min-w-0">
                <p className="truncate font-semibold text-[var(--color-text)]">
                  {gym.name}
                </p>
                <div className="mt-1 flex flex-wrap gap-2 text-xs">
                  {gym.isCurrent ? (
                    <span className="rounded-md bg-[var(--color-primary)]/15 px-2 py-0.5 font-medium text-[var(--color-primary)]">
                      {labels.currentGym}
                    </span>
                  ) : null}
                  {gym.deleted_at ? (
                    <span className="rounded-md bg-[var(--color-danger)]/10 px-2 py-0.5 font-medium text-[var(--color-danger)]">
                      {labels.scheduledDeletion.replace(
                        "{date}",
                        retentionDate(gym.deleted_at, locale),
                      )}
                    </span>
                  ) : null}
                </div>
              </div>
              <div className="flex flex-wrap gap-2">
                {gym.deleted_at ? (
                  <form action={gymCancelAction}>
                    <input type="hidden" name="locale" value={locale} />
                    <input type="hidden" name="gym_id" value={gym.id} />
                    <Button
                      type="submit"
                      variant="ghost"
                      className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold"
                      disabled={gymCancelPending}
                    >
                      <RotateCcw className="h-3.5 w-3.5" aria-hidden />
                      {labels.cancelDeletion}
                    </Button>
                  </form>
                ) : (
                  <Button
                    type="button"
                    variant="ghost"
                    className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold text-[var(--color-danger)] hover:text-[var(--color-danger)]"
                    onClick={() => setDeleteGym(gym)}
                  >
                    <Trash2 className="h-3.5 w-3.5" aria-hidden />
                    {labels.deleteGym}
                  </Button>
                )}
              </div>
            </li>
          ))}
        </ul>
      </section>

      <section
        id="danger"
        className="scroll-mt-6 rounded-2xl border border-[var(--color-danger)]/30 bg-[var(--color-surface)] p-5 shadow-sm sm:p-6"
      >
        <div className="mb-4 flex items-start gap-3">
          <div className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[var(--color-danger)]/10 text-[var(--color-danger)]">
            <AlertTriangle className="h-5 w-5" aria-hidden />
          </div>
          <div>
            <h2 className="font-title text-xl font-bold text-[var(--color-text)]">
              {labels.dangerTitle}
            </h2>
            <p className="mt-1 text-sm text-[var(--color-muted)]">
              {labels.dangerHint}
            </p>
            <p className="mt-2 text-xs text-[var(--color-muted)]">
              {labels.retentionNote.replace(
                "{days}",
                String(ORG_DELETION_RETENTION_DAYS),
              )}
            </p>
          </div>
        </div>
        <Button
          type="button"
          variant="ghost"
          className="rounded-lg border border-[var(--color-danger)]/40 px-4 py-2.5 text-sm font-semibold text-[var(--color-danger)] hover:bg-[var(--color-danger)]/10 hover:text-[var(--color-danger)]"
          onClick={() => setDeleteOrgOpen(true)}
        >
          {labels.deleteOrg}
        </Button>
      </section>

      <Dialog
        open={createOpen}
        onOpenChange={setCreateOpen}
        title={labels.addGymTitle}
        description={labels.addGymDescription}
        closeLabel={labels.close}
        className="max-w-lg"
      >
        <form action={createAction} className="flex flex-col gap-4" noValidate>
          <input type="hidden" name="locale" value={locale} />
          <FormField label={labels.gymName}>
            <Input
              required
              name="name"
              maxLength={LIMITS.entityName}
              autoComplete="organization"
            />
          </FormField>
          <p className="text-sm text-[var(--color-muted)]">
            {labels.createGymComingSoon}
          </p>
          <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
            <Button
              type="button"
              variant="ghost"
              className="rounded-lg px-4 py-2.5 text-sm font-semibold"
              onClick={() => setCreateOpen(false)}
            >
              {labels.cancel}
            </Button>
            <Button type="submit" variant="primary" className="mt-0" disabled={createPending}>
              {labels.save}
            </Button>
          </div>
        </form>
      </Dialog>

      <Dialog
        open={deleteGym != null}
        onOpenChange={(open) => {
          if (!open) setDeleteGym(null);
        }}
        title={labels.deleteGymTitle}
        description={labels.deleteGymHint}
        closeLabel={labels.close}
        className="max-w-lg"
      >
        {deleteGym ? (
          <form action={gymDeleteAction} className="flex flex-col gap-4" noValidate>
            <input type="hidden" name="locale" value={locale} />
            <input type="hidden" name="gym_id" value={deleteGym.id} />
            <FormField label={labels.confirmName}>
              <Input
                required
                name="confirm_name"
                maxLength={LIMITS.entityName}
                placeholder={labels.confirmNamePlaceholder.replace(
                  "{name}",
                  deleteGym.name,
                )}
                autoComplete="off"
              />
            </FormField>
            <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
              <Button
                type="button"
                variant="ghost"
                className="rounded-lg px-4 py-2.5 text-sm font-semibold"
                onClick={() => setDeleteGym(null)}
              >
                {labels.cancel}
              </Button>
              <Button
                type="submit"
                variant="primary"
                className="mt-0 bg-[var(--color-danger)] hover:bg-[var(--color-danger)]"
                disabled={gymDeletePending}
              >
                {labels.confirmDelete}
              </Button>
            </div>
          </form>
        ) : null}
      </Dialog>

      <Dialog
        open={deleteOrgOpen}
        onOpenChange={setDeleteOrgOpen}
        title={labels.deleteOrgTitle}
        description={labels.deleteOrgHint}
        closeLabel={labels.close}
        className="max-w-lg"
      >
        <form action={orgDeleteAction} className="flex flex-col gap-4" noValidate>
          <input type="hidden" name="locale" value={locale} />
          <FormField label={labels.confirmName}>
            <Input
              required
              name="confirm_name"
              maxLength={LIMITS.entityName}
              placeholder={labels.confirmNamePlaceholder.replace(
                "{name}",
                organizationName,
              )}
              autoComplete="off"
            />
          </FormField>
          <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
            <Button
              type="button"
              variant="ghost"
              className="rounded-lg px-4 py-2.5 text-sm font-semibold"
              onClick={() => setDeleteOrgOpen(false)}
            >
              {labels.cancel}
            </Button>
            <Button
              type="submit"
              variant="primary"
              className="mt-0 bg-[var(--color-danger)] hover:bg-[var(--color-danger)]"
              disabled={orgDeletePending}
            >
              {labels.confirmDelete}
            </Button>
          </div>
        </form>
      </Dialog>
    </div>
  );
}

// src/lib/components/organization/OrganizationClient.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import AlertTriangle from '@lucide/svelte/icons/alert-triangle';
	import ArrowUpRight from '@lucide/svelte/icons/arrow-up-right';
	import Building2 from '@lucide/svelte/icons/building-2';
	import Plus from '@lucide/svelte/icons/plus';
	import RotateCcw from '@lucide/svelte/icons/rotate-ccw';
	import Trash2 from '@lucide/svelte/icons/trash-2';
	import Button from '$lib/components/ui/Button.svelte';
	import Dialog from '$lib/components/ui/Dialog.svelte';
	import FormField from '$lib/components/ui/FormField.svelte';
	import Input from '$lib/components/ui/Input.svelte';
	import type { Locale } from '$lib/i18n/config';
	import type { Dictionary } from '$lib/i18n/dictionaries';
	import { formatMoney } from '$lib/i18n/money';
	import {
		AMRAP_PLANS,
		ORG_DELETION_RETENTION_DAYS,
		canCreateGym,
		maxGyms
	} from '$lib/plans/limits';
	import type { OrgActionState } from '$lib/server/organization/actions';
	import type { OrgPlanTier } from '$lib/types';
	import { LIMITS } from '$lib/validation/schemas';

	export type OrgGymRow = {
		id: string;
		name: string;
		deleted_at: string | null;
		isCurrent: boolean;
	};

	type Props = {
		locale: Locale;
		d: Dictionary;
		organizationName: string;
		planTier: OrgPlanTier;
		gyms: OrgGymRow[];
	};

	let { locale, d, organizationName, planTier, gyms }: Props = $props();

	const labels = $derived(d.organization);
	const contactHref = $derived(`/${locale}#contacto`);

	/** Soft-delete gym / org UI — re-enable when product is ready. */
	const showDeletionUi = false;

	let createOpen = $state(false);
	let deleteGym = $state<OrgGymRow | null>(null);
	let deleteOrgOpen = $state(false);
	let orgConfirmName = $state('');
	let gymConfirmName = $state('');
	let upgradeTier = $state<OrgPlanTier | null>(null);

	let flash = $state<string | undefined>(undefined);
	let flashError = $state<string | undefined>(undefined);
	let checkoutPending = $state(false);
	let createPending = $state(false);
	let gymDeletePending = $state(false);
	let gymCancelPending = $state(false);
	let orgDeletePending = $state(false);

	const activeGymCount = $derived(gyms.filter((g) => !g.deleted_at).length);
	const gymCap = $derived(maxGyms(planTier));
	const canAddGym = $derived(canCreateGym(planTier, activeGymCount));
	const needsUpgradeForGym = $derived(!canAddGym);

	const upgradePlanLabel = $derived(
		upgradeTier != null ? planLabel(upgradeTier) : ''
	);

	function planLabel(tier: OrgPlanTier) {
		switch (tier) {
			case 'STARTER':
				return labels.planStarter;
			case 'GROWTH':
				return labels.planGrowth;
			case 'PRO':
				return labels.planPro;
			default:
				return labels.planFreemium;
		}
	}

	function priceLine(tier: OrgPlanTier): { amount: string; note: string } {
		const plan = AMRAP_PLANS.find((p) => p.tier === tier)!;
		if (plan.priceNote === 'free') {
			return { amount: formatMoney(0, locale), note: labels.perMonth };
		}
		if (plan.priceNote === 'contact') {
			return { amount: labels.priceContact, note: labels.contactSales };
		}
		const amountMxn = plan.priceMxnMonthly ?? 0;
		const amountUsd = plan.priceUsdMonthly ?? 0;
		const amount = formatMoney(locale === 'en' ? amountUsd : amountMxn, locale);
		const note =
			plan.priceNote === 'per_org'
				? `${labels.perMonth} · ${labels.pricePerOrg}`
				: `${labels.perMonth} · ${labels.pricePerGym}`;
		return { amount, note };
	}

	function retentionDate(iso: string) {
		const base = new Date(iso);
		base.setDate(base.getDate() + ORG_DELETION_RETENTION_DAYS);
		try {
			return base.toLocaleDateString(locale, {
				day: '2-digit',
				month: 'short',
				year: 'numeric'
			});
		} catch {
			return base.toISOString().slice(0, 10);
		}
	}

	function applyState(data: OrgActionState) {
		if (!data) return;
		if (data.error) {
			flashError = data.error;
			flash = undefined;
		} else if (data.message) {
			flash = data.message;
			flashError = undefined;
		}
	}

	function openUpgradeConfirm(tier: OrgPlanTier) {
		upgradeTier = tier;
	}
</script>

<div class="flex flex-col gap-5">
	<header>
		<h1 class="font-title text-3xl font-bold tracking-tight text-[var(--color-text)]">
			{labels.title}
		</h1>
		<p class="mt-1 text-sm text-[var(--color-muted)]">{labels.subtitle}</p>
		<p
			class="mt-3 flex w-full items-center gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2.5 text-sm font-semibold text-[var(--color-text)] shadow-sm"
		>
			<Building2 class="h-4 w-4 shrink-0 text-[var(--color-primary)]" aria-hidden="true" />
			<span class="min-w-0 flex-1 truncate">{organizationName}</span>
			<span
				class="shrink-0 rounded-md bg-[var(--color-primary)]/15 px-2 py-0.5 text-xs font-bold text-[var(--color-primary)]"
			>
				{planLabel(planTier)}
			</span>
		</p>
	</header>

	{#if flashError || flash}
		<p
			class="rounded-lg border px-4 py-3 text-sm font-medium {flashError
				? 'border-[var(--color-danger)]/25 bg-[var(--color-danger)]/10 text-[var(--color-danger)]'
				: 'border-[var(--color-success)]/25 bg-[var(--color-success)]/10 text-[var(--color-success)]'}"
			role="status"
		>
			{flashError ?? flash}
		</p>
	{/if}

	<section
		id="gyms"
		class="scroll-mt-6 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 shadow-sm sm:p-6"
	>
		<div class="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
			<div>
				<h2 class="font-title text-xl font-bold text-[var(--color-text)]">{labels.gymsTitle}</h2>
				<p class="mt-1 text-sm text-[var(--color-muted)]">{labels.gymsHint}</p>
				{#if gymCap != null}
					<p class="mt-2 text-xs font-medium text-[var(--color-muted)]">
						{labels.gymQuota
							.replace('{used}', String(activeGymCount))
							.replace('{max}', String(gymCap))}
					</p>
				{/if}
				{#if needsUpgradeForGym}
					<p class="mt-2 text-sm text-[var(--color-muted)]">{labels.gymCapContact}</p>
				{/if}
			</div>
			{#if !needsUpgradeForGym}
				<Button type="button" variant="toolbar" class="mt-0" onclick={() => (createOpen = true)}>
					<Plus class="h-4 w-4 shrink-0" aria-hidden="true" />
					<span class="shrink-0">{labels.addGym}</span>
				</Button>
			{/if}
		</div>

		<ul class="divide-y divide-[var(--color-border)] rounded-xl border border-[var(--color-border)]">
			{#each gyms as gym (gym.id)}
				<li class="flex flex-row items-center gap-3 px-4 py-3">
					<div class="min-w-0 flex-1">
						<p class="flex min-w-0 flex-wrap items-center gap-2">
							<span class="truncate font-semibold text-[var(--color-text)]">{gym.name}</span>
							{#if gym.isCurrent}
								<span
									class="shrink-0 rounded-md bg-[var(--color-primary)]/15 px-2 py-0.5 text-xs font-medium text-[var(--color-primary)]"
								>
									{labels.currentGym}
								</span>
							{/if}
						</p>
						{#if gym.deleted_at}
							<p class="mt-1 text-xs">
								<span
									class="rounded-md bg-[var(--color-danger)]/10 px-2 py-0.5 font-medium text-[var(--color-danger)]"
								>
									{labels.scheduledDeletion.replace('{date}', retentionDate(gym.deleted_at))}
								</span>
							</p>
						{/if}
					</div>
					{#if showDeletionUi || gym.deleted_at}
						<div class="ml-auto flex shrink-0 items-center">
							{#if gym.deleted_at}
								<form
									method="POST"
									action="?/cancelGymDelete"
									use:enhance={() => {
										gymCancelPending = true;
										return async ({ result, update }) => {
											gymCancelPending = false;
											await update();
											if (result.type === 'success') applyState(result.data as OrgActionState);
										};
									}}
								>
									<input type="hidden" name="locale" value={locale} />
									<input type="hidden" name="gym_id" value={gym.id} />
									<button
										type="submit"
										disabled={gymCancelPending}
										class="inline-flex h-11 w-11 items-center justify-center rounded-lg text-[var(--color-text)] transition-colors hover:bg-[var(--color-surface-hover)] disabled:opacity-60"
										aria-label={labels.cancelDeletion}
										title={labels.cancelDeletion}
									>
										<RotateCcw class="h-4 w-4" aria-hidden="true" />
									</button>
								</form>
							{:else if showDeletionUi}
								<button
									type="button"
									class="inline-flex h-11 w-11 items-center justify-center rounded-lg text-[var(--color-danger)] transition-colors hover:bg-[var(--color-danger)]/10"
									aria-label={labels.deleteGym}
									title={labels.deleteGym}
									onclick={() => {
										deleteGym = gym;
										gymConfirmName = '';
									}}
								>
									<Trash2 class="h-4 w-4" aria-hidden="true" />
								</button>
							{/if}
						</div>
					{/if}
				</li>
			{/each}
		</ul>
	</section>

	<div class="flex items-center gap-3 px-1" role="separator" aria-label={labels.subscriptionTitle}>
		<div class="h-px flex-1 bg-[var(--color-border)]"></div>
		<span
			class="shrink-0 text-[11px] font-bold uppercase tracking-wider text-[var(--color-muted)]"
		>
			{labels.subscriptionTitle}
		</span>
		<div class="h-px flex-1 bg-[var(--color-border)]"></div>
	</div>

	<section
		id="subscription"
		class="scroll-mt-6 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4 shadow-sm sm:p-5"
	>
		<p class="mb-3 text-xs text-[var(--color-muted)]">
			{labels.currentPlan}:
			<span class="font-semibold text-[var(--color-text)]">{planLabel(planTier)}</span>
		</p>

		<ul class="flex flex-col gap-2">
			{#each AMRAP_PLANS as plan (plan.tier)}
				{@const isCurrent = plan.tier === planTier}
				{@const pricing = priceLine(plan.tier)}
				{@const isContact = plan.priceNote === 'contact'}
				{@const canAct = plan.tier !== 'FREEMIUM' && !isCurrent}
				{@const rowClass = `group flex min-h-[var(--touch-target)] w-full items-center gap-3 rounded-xl border px-3 py-2.5 text-left transition-colors sm:gap-4 sm:px-4 ${
					isCurrent
						? 'border-[var(--color-primary)]/50 bg-[var(--color-primary)]/5'
						: canAct
							? 'border-[var(--color-border)] bg-[var(--color-surface-hover)]/40 hover:border-[var(--color-primary)]/40 hover:bg-[var(--color-primary)]/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary)]'
							: 'border-[var(--color-border)]/80'
				}`}

				<li>
					{#if canAct && isContact}
						<a href={contactHref} class={rowClass}>
							<div class="min-w-0 flex-1">
								<div class="flex min-w-0 flex-wrap items-center gap-2">
									<span class="text-sm font-semibold text-[var(--color-text)]"
										>{planLabel(plan.tier)}</span
									>
								</div>
								<p class="mt-0.5 truncate text-xs text-[var(--color-muted)]">
									<span class="font-semibold tabular-nums text-[var(--color-text)]"
										>{pricing.amount}</span
									>
									<span class="text-[var(--color-muted)]"> · {pricing.note}</span>
								</p>
							</div>
							<span
								class="inline-flex h-10 shrink-0 items-center gap-1.5 rounded-lg border border-[var(--color-primary)]/30 bg-[var(--color-primary)]/10 px-3 text-xs font-bold text-[var(--color-primary)] transition-colors group-hover:bg-[var(--color-primary)] group-hover:text-[var(--color-primary-on)]"
							>
								{labels.contactSales}
								<ArrowUpRight class="h-3.5 w-3.5" aria-hidden="true" />
							</span>
						</a>
					{:else if canAct}
						<button
							type="button"
							class={rowClass}
							onclick={() => openUpgradeConfirm(plan.tier)}
						>
							<div class="min-w-0 flex-1">
								<div class="flex min-w-0 flex-wrap items-center gap-2">
									<span class="text-sm font-semibold text-[var(--color-text)]"
										>{planLabel(plan.tier)}</span
									>
								</div>
								<p class="mt-0.5 truncate text-xs text-[var(--color-muted)]">
									<span class="font-semibold tabular-nums text-[var(--color-text)]"
										>{pricing.amount}</span
									>
									<span class="text-[var(--color-muted)]"> · {pricing.note}</span>
								</p>
							</div>
							<span
								class="inline-flex h-10 shrink-0 items-center gap-1.5 rounded-lg bg-[var(--color-primary)] px-3.5 text-xs font-bold text-[var(--color-primary-on)] shadow-sm transition-colors group-hover:bg-[var(--color-primary-hover)]"
							>
								{labels.upgrade}
							</span>
						</button>
					{:else}
						<div class={rowClass} aria-current={isCurrent ? 'true' : undefined}>
							<div class="min-w-0 flex-1">
								<div class="flex min-w-0 flex-wrap items-center gap-2">
									<span class="text-sm font-semibold text-[var(--color-text)]"
										>{planLabel(plan.tier)}</span
									>
									{#if isCurrent}
										<span
											class="rounded-full bg-[var(--color-success)]/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-[var(--color-success)]"
										>
											{labels.current}
										</span>
									{/if}
								</div>
								<p class="mt-0.5 truncate text-xs text-[var(--color-muted)]">
									<span class="font-semibold tabular-nums text-[var(--color-text)]"
										>{pricing.amount}</span
									>
									<span class="text-[var(--color-muted)]"> · {pricing.note}</span>
								</p>
							</div>
						</div>
					{/if}
				</li>
			{/each}
		</ul>
	</section>

	{#if showDeletionUi}
		<section
			id="danger"
			class="scroll-mt-6 rounded-2xl border border-[var(--color-danger)]/30 bg-[var(--color-surface)] p-5 shadow-sm sm:p-6"
		>
			<div class="flex flex-row items-center justify-between gap-3">
				<div class="flex min-w-0 flex-1 items-start gap-3">
					<div
						class="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[var(--color-danger)]/10 text-[var(--color-danger)]"
					>
						<AlertTriangle class="h-5 w-5" aria-hidden="true" />
					</div>
					<div class="min-w-0">
						<h2 class="font-title text-xl font-bold text-[var(--color-text)]">{labels.dangerTitle}</h2>
						<p class="mt-1 text-sm text-[var(--color-muted)]">{labels.dangerHint}</p>
						<p class="mt-2 text-xs text-[var(--color-muted)]">
							{labels.retentionNote.replace('{days}', String(ORG_DELETION_RETENTION_DAYS))}
						</p>
					</div>
				</div>
				<button
					type="button"
					class="inline-flex h-11 w-11 shrink-0 items-center justify-center gap-1.5 self-center rounded-lg bg-[var(--color-danger)] text-white shadow-sm transition-colors hover:bg-[var(--color-danger)]/90 focus:outline-none focus:ring-2 focus:ring-[var(--color-danger)] focus:ring-offset-2 focus:ring-offset-[var(--color-bg)] sm:w-auto sm:px-4"
					aria-label={labels.deleteOrg}
					onclick={() => {
						deleteOrgOpen = true;
						orgConfirmName = '';
					}}
				>
					<Trash2 class="h-4 w-4" aria-hidden="true" />
					<span class="hidden sm:inline">{labels.deleteOrg}</span>
				</button>
			</div>
		</section>
	{/if}

	<Dialog
		open={upgradeTier != null}
		onOpenChange={(open) => {
			if (!open) upgradeTier = null;
		}}
		title={labels.upgradeConfirmTitle}
		description={labels.upgradeConfirmDescription.replace('{plan}', upgradePlanLabel)}
		closeLabel={labels.close}
		class="max-w-md"
	>
		{#if upgradeTier}
			<form
				method="POST"
				action="?/checkout"
				class="flex flex-col gap-4"
				use:enhance={() => {
					checkoutPending = true;
					return async ({ result, update }) => {
						checkoutPending = false;
						await update();
						if (result.type === 'success') {
							applyState(result.data as OrgActionState);
							upgradeTier = null;
						}
					};
				}}
			>
				<input type="hidden" name="locale" value={locale} />
				<input type="hidden" name="tier" value={upgradeTier} />
				<div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
					<Button
						type="button"
						variant="ghost"
						class="rounded-lg px-4 py-2.5 text-sm font-semibold"
						onclick={() => (upgradeTier = null)}
					>
						{labels.cancel}
					</Button>
					<Button type="submit" class="mt-0" disabled={checkoutPending}>
						{checkoutPending ? labels.save : labels.upgradeConfirmSubmit}
					</Button>
				</div>
			</form>
		{/if}
	</Dialog>

	<Dialog
		open={createOpen}
		onOpenChange={(open) => (createOpen = open)}
		title={labels.addGymTitle}
		description={labels.addGymDescription}
		closeLabel={labels.close}
		class="max-w-lg"
	>
		<form
			method="POST"
			action="?/createGym"
			class="flex flex-col gap-4"
			novalidate
			use:enhance={() => {
				createPending = true;
				return async ({ result, update }) => {
					createPending = false;
					await update();
					if (result.type === 'success') {
						applyState(result.data as OrgActionState);
						const data = result.data as OrgActionState;
						if (data?.success) createOpen = false;
					}
				};
			}}
		>
			<input type="hidden" name="locale" value={locale} />
			<FormField label={labels.gymName} htmlFor="org-gym-name">
				{#snippet children({ invalid, describedBy })}
					<Input
						id="org-gym-name"
						name="name"
						required
						maxlength={LIMITS.entityName}
						autocomplete="organization"
						{invalid}
						{describedBy}
					/>
				{/snippet}
			</FormField>
			<p class="text-sm text-[var(--color-muted)]">{labels.createGymComingSoon}</p>
			<div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
				<Button
					type="button"
					variant="ghost"
					class="rounded-lg px-4 py-2.5 text-sm font-semibold"
					onclick={() => (createOpen = false)}
				>
					{labels.cancel}
				</Button>
				<Button type="submit" class="mt-0" disabled={createPending}>{labels.save}</Button>
			</div>
		</form>
	</Dialog>

	{#if showDeletionUi}
		<Dialog
			open={deleteGym != null}
			onOpenChange={(open) => {
				if (!open) {
					deleteGym = null;
					gymConfirmName = '';
				}
			}}
			title={labels.deleteGymTitle}
			description={labels.deleteGymHint}
			closeLabel={labels.close}
			class="max-w-md"
			containerClass="items-center justify-center p-[var(--spacing-page)] sm:p-6"
		>
			{#if deleteGym}
				{@const gymToDelete = deleteGym}
				<form
					method="POST"
					action="?/deleteGym"
					class="flex flex-col gap-4"
					novalidate
					use:enhance={() => {
						gymDeletePending = true;
						return async ({ result, update }) => {
							gymDeletePending = false;
							await update();
							if (result.type === 'success') {
								applyState(result.data as OrgActionState);
								const data = result.data as OrgActionState;
								if (data?.success) {
									deleteGym = null;
									gymConfirmName = '';
								}
							}
						};
					}}
				>
					<input type="hidden" name="locale" value={locale} />
					<input type="hidden" name="gym_id" value={gymToDelete.id} />
					<FormField label={labels.confirmName} htmlFor="org-gym-confirm">
						{#snippet children({ invalid, describedBy })}
							<Input
								id="org-gym-confirm"
								name="confirm_name"
								required
								maxlength={LIMITS.entityName}
								placeholder={labels.confirmNamePlaceholder.replace('{name}', gymToDelete.name)}
								autocomplete="off"
								bind:value={gymConfirmName}
								{invalid}
								{describedBy}
							/>
						{/snippet}
					</FormField>
					<div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
						<Button
							type="button"
							variant="ghost"
							class="rounded-lg px-4 py-2.5 text-sm font-semibold"
							onclick={() => {
								deleteGym = null;
								gymConfirmName = '';
							}}
						>
							{labels.cancel}
						</Button>
						<Button
							type="submit"
							class="mt-0 bg-[var(--color-danger)] hover:bg-[var(--color-danger)]"
							disabled={gymDeletePending ||
								gymConfirmName.trim().toLowerCase() !== gymToDelete.name.trim().toLowerCase()}
						>
							{labels.confirmDelete}
						</Button>
					</div>
				</form>
			{/if}
		</Dialog>

		<Dialog
			open={deleteOrgOpen}
			onOpenChange={(open) => {
				deleteOrgOpen = open;
				if (!open) orgConfirmName = '';
			}}
			title={labels.deleteOrgTitle}
			description={labels.deleteOrgHint}
			closeLabel={labels.close}
			class="max-w-md"
			containerClass="items-center justify-center p-[var(--spacing-page)] sm:p-6"
		>
			<form
				method="POST"
				action="?/deleteOrg"
				class="flex flex-col gap-4"
				novalidate
				use:enhance={() => {
					orgDeletePending = true;
					return async ({ result, update }) => {
						orgDeletePending = false;
						await update();
						if (result.type === 'success') applyState(result.data as OrgActionState);
					};
				}}
			>
				<input type="hidden" name="locale" value={locale} />
				<FormField label={labels.confirmName} htmlFor="org-confirm">
					{#snippet children({ invalid, describedBy })}
						<Input
							id="org-confirm"
							name="confirm_name"
							required
							maxlength={LIMITS.entityName}
							placeholder={labels.confirmNamePlaceholder.replace('{name}', organizationName)}
							autocomplete="off"
							bind:value={orgConfirmName}
							{invalid}
							{describedBy}
						/>
					{/snippet}
				</FormField>
				<div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
					<Button
						type="button"
						variant="ghost"
						class="rounded-lg px-4 py-2.5 text-sm font-semibold"
						onclick={() => {
							deleteOrgOpen = false;
							orgConfirmName = '';
						}}
					>
						{labels.cancel}
					</Button>
					<Button
						type="submit"
						class="mt-0 bg-[var(--color-danger)] hover:bg-[var(--color-danger)]"
						disabled={orgDeletePending ||
							orgConfirmName.trim().toLowerCase() !== organizationName.trim().toLowerCase()}
					>
						{labels.confirmDelete}
					</Button>
				</div>
			</form>
		</Dialog>
	{/if}
</div>
