// amrap-next/app/[locale]/(app)/timers/page.tsx
import { redirect, notFound } from "next/navigation";
import { getWorkspace } from "@/lib/auth/session";
import { canInWorkspace } from "@/lib/auth/permissions";
import type { Locale } from "@/lib/i18n/config";
import { isLocale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";
import { TimerApp } from "@/components/timers/timer-app";

export default async function OpsTimersPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale: raw } = await params;
  if (!isLocale(raw)) notFound();
  const locale = raw as Locale;
  const d = getDictionary(locale);

  const workspace = await getWorkspace();
  if (!workspace) redirect(`/${locale}/login`);
  if (!canInWorkspace(workspace, "use_timers")) {
    return (
      <p className="text-[var(--color-muted)]">{d.common.forbidden}</p>
    );
  }

  return (
    <div className="mx-auto w-full max-w-3xl">
      <TimerApp locale={locale} />
    </div>
  );
}

// src/routes/[locale]/(ops)/timers/+page.svelte
<script lang="ts">
	import TimerApp from '$lib/components/timers/TimerApp.svelte';
	import type { PageProps } from './$types';

	let { data }: PageProps = $props();
	const d = $derived(data.d!);
</script>

<svelte:head>
	<title>{d.nav.timers} — AMRAP</title>
</svelte:head>

{#if 'forbidden' in data && data.forbidden}
	<p class="text-[var(--color-muted)]">{d.common.forbidden}</p>
{:else}
	<div class="mx-auto w-full max-w-3xl animate-fade-in-up">
		<TimerApp locale={data.locale} />
	</div>
{/if}
