// components/dashboard-quick-actions.tsx
"use client";

import Link from "next/link";
import { Briefcase, Dumbbell, QrCode, UserPlus } from "lucide-react";
import type { Locale } from "@/lib/i18n/config";
import {
  RegisterUserButton,
  type RegisterPlanOption,
} from "@/components/register-user-dialog";

type Props = {
  locale: Locale;
  canCheckIn: boolean;
  canManageMembers: boolean;
  canManageStaff: boolean;
  plans: RegisterPlanOption[];
  labels: {
    quickActions: string;
    quickCheckIn: string;
    quickNewMember: string;
    quickNewTrainer: string;
    quickNewStaff: string;
  };
};

export function DashboardQuickActions({
  locale,
  canCheckIn,
  canManageMembers,
  canManageStaff,
  plans,
  labels,
}: Props) {
  const prefix = `/${locale}`;

  return (
    <section
      aria-label={labels.quickActions}
      className="grid w-full grid-cols-2 gap-2 lg:grid-cols-4"
    >
      {canCheckIn ? (
        <Link
          href={`${prefix}/checkin`}
          className="inline-flex w-full items-center justify-center gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3.5 py-2.5 text-sm font-semibold text-[var(--color-text)] shadow-sm transition-colors hover:border-[var(--color-primary)]/40 hover:bg-[var(--color-surface-hover)]"
        >
          <QrCode className="h-4 w-4 text-[var(--color-primary)]" aria-hidden />
          {labels.quickCheckIn}
        </Link>
      ) : null}
      {canManageMembers ? (
        <RegisterUserButton
          locale={locale}
          canManageMembers
          canManageStaff={false}
          plans={plans}
          defaultRole="member"
          allowedRoles={["member"]}
          label={labels.quickNewMember}
          appearance="quickAction"
          icon={
            <UserPlus className="h-4 w-4 text-[var(--color-primary)]" aria-hidden />
          }
        />
      ) : null}
      {canManageStaff ? (
        <RegisterUserButton
          locale={locale}
          canManageMembers={false}
          canManageStaff
          defaultRole="trainer"
          allowedRoles={["trainer"]}
          label={labels.quickNewTrainer}
          appearance="quickAction"
          icon={
            <Dumbbell className="h-4 w-4 text-[var(--color-primary)]" aria-hidden />
          }
        />
      ) : null}
      {canManageStaff ? (
        <RegisterUserButton
          locale={locale}
          canManageMembers={false}
          canManageStaff
          defaultRole="staff"
          allowedRoles={["staff"]}
          label={labels.quickNewStaff}
          appearance="quickAction"
          icon={
            <Briefcase
              className="h-4 w-4 text-[var(--color-primary)]"
              aria-hidden
            />
          }
        />
      ) : null}
    </section>
  );
}

// src/lib/components/dashboard/DashboardQuickActions.svelte
<script lang="ts">
	import Briefcase from '@lucide/svelte/icons/briefcase';
	import Dumbbell from '@lucide/svelte/icons/dumbbell';
	import QrCode from '@lucide/svelte/icons/qr-code';
	import UserPlus from '@lucide/svelte/icons/user-plus';
	import RegisterUserButton from '$lib/components/register/RegisterUserButton.svelte';
	import type { RegisterPlanOption } from '$lib/components/register/RegisterUserDialog.svelte';
	import type { Locale } from '$lib/i18n/config';

	type Props = {
		locale: Locale;
		canCheckIn: boolean;
		canManageMembers: boolean;
		canManageStaff: boolean;
		plans: RegisterPlanOption[];
		labels: {
			quickActions: string;
			quickCheckIn: string;
			quickNewMember: string;
			quickNewTrainer: string;
			quickNewStaff: string;
		};
	};

	let { locale, canCheckIn, canManageMembers, canManageStaff, plans, labels }: Props = $props();

	const prefix = $derived(`/${locale}`);
	const actionClass =
		'inline-flex w-full items-center justify-center gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3.5 py-2.5 text-sm font-semibold text-[var(--color-text)] shadow-sm transition-colors hover:border-[var(--color-primary)]/40 hover:bg-[var(--color-surface-hover)]';
</script>

<section aria-label={labels.quickActions} class="grid w-full grid-cols-2 gap-2 lg:grid-cols-4">
	{#if canCheckIn}
		<a href="{prefix}/checkin" class={actionClass}>
			<QrCode class="h-4 w-4 text-[var(--color-primary)]" aria-hidden="true" />
			{labels.quickCheckIn}
		</a>
	{/if}
	{#if canManageMembers}
		<RegisterUserButton
			{locale}
			canManageMembers
			canManageStaff={false}
			{plans}
			defaultRole="member"
			allowedRoles={['member']}
			label={labels.quickNewMember}
			appearance="quickAction"
		>
			{#snippet icon()}
				<UserPlus class="h-4 w-4 text-[var(--color-primary)]" aria-hidden="true" />
			{/snippet}
		</RegisterUserButton>
	{/if}
	{#if canManageStaff}
		<RegisterUserButton
			{locale}
			canManageMembers={false}
			canManageStaff
			defaultRole="trainer"
			allowedRoles={['trainer']}
			label={labels.quickNewTrainer}
			appearance="quickAction"
		>
			{#snippet icon()}
				<Dumbbell class="h-4 w-4 text-[var(--color-primary)]" aria-hidden="true" />
			{/snippet}
		</RegisterUserButton>
		<RegisterUserButton
			{locale}
			canManageMembers={false}
			canManageStaff
			defaultRole="staff"
			allowedRoles={['staff']}
			label={labels.quickNewStaff}
			appearance="quickAction"
		>
			{#snippet icon()}
				<Briefcase class="h-4 w-4 text-[var(--color-primary)]" aria-hidden="true" />
			{/snippet}
		</RegisterUserButton>
	{/if}
</section>
