// components/theme-toggle.tsx
"use client";

import { Moon, Sun } from "lucide-react";
import { useTheme } from "next-themes";
import { useSyncExternalStore } from "react";

type Props = {
  className?: string;
};

export function ThemeToggle({ className = "" }: Props) {
  const { setTheme, resolvedTheme } = useTheme();
  const mounted = useSyncExternalStore(
    () => () => {},
    () => true,
    () => false,
  );

  if (!mounted) {
    return (
      <span
        className={`inline-flex h-9 w-9 shrink-0 rounded-full ${className}`}
        aria-hidden
      />
    );
  }

  const isDark = resolvedTheme === "dark";

  return (
    <button
      type="button"
      onClick={() => setTheme(isDark ? "light" : "dark")}
      className={`relative inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-[var(--color-muted)] transition-colors hover:bg-[var(--color-surface-hover)] hover:text-[var(--color-text)] ${className}`}
      aria-label={isDark ? "Switch to light mode" : "Switch to dark mode"}
    >
      <Sun className="h-5 w-5 scale-100 transition-all dark:scale-0 dark:opacity-0" />
      <Moon className="absolute h-5 w-5 scale-0 opacity-0 transition-all dark:scale-100 dark:opacity-100" />
    </button>
  );
}

// src/lib/components/landing/ThemeToggle.svelte
<script lang="ts">
	import { Moon, Sun } from '@lucide/svelte';
	import { onMount } from 'svelte';
	import { initTheme, resolveTheme, toggleTheme, type Theme } from '$lib/theme';

	type Props = {
		label: string;
		class?: string;
	};

	let { label, class: className = '' }: Props = $props();

	let theme = $state<Theme>('light');

	onMount(() => {
		initTheme();
		theme = resolveTheme();
	});

	function handleToggle() {
		theme = toggleTheme(theme);
	}
</script>

<button
	type="button"
	onclick={handleToggle}
	class="relative inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-[var(--color-muted)] transition-colors hover:bg-[var(--color-surface-hover)] hover:text-[var(--color-text)] {className}"
	aria-label={label}
>
	<Moon class="h-5 w-5 scale-100 transition-all dark:scale-0 dark:opacity-0" aria-hidden="true" />
	<Sun
		class="absolute h-5 w-5 scale-0 opacity-0 transition-all dark:scale-100 dark:opacity-100"
		aria-hidden="true"
	/>
</button>
