// src/lib/components/ui/Input.svelte
<script lang="ts">
	type Props = {
		id: string;
		name: string;
		type?: string;
		value?: string;
		placeholder?: string;
		maxlength?: number;
		min?: string | number;
		max?: string | number;
		step?: string | number;
		required?: boolean;
		autocomplete?: string;
		inputmode?: 'email' | 'text' | 'decimal' | 'numeric';
		spellcheck?: boolean;
		invalid?: boolean;
		describedBy?: string;
		class?: string;
		oninput?: (event: Event) => void;
	};

	let {
		id,
		name,
		type = 'text',
		value = $bindable(''),
		placeholder = undefined,
		maxlength = undefined,
		min = undefined,
		max = undefined,
		step = undefined,
		required = false,
		autocomplete = undefined,
		inputmode = undefined,
		spellcheck = undefined,
		invalid = false,
		describedBy = undefined,
		class: className = '',
		oninput
	}: Props = $props();

	const baseClass =
		'w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-hover)] px-4 py-2.5 text-[var(--color-text)] placeholder-[var(--color-muted)] transition-colors focus:border-[var(--color-ring)] focus:outline-none focus:ring-1 focus:ring-[var(--color-ring)]';
</script>

<input
	{id}
	{name}
	{type}
	bind:value
	{placeholder}
	{maxlength}
	min={min}
	max={max}
	step={step}
	{required}
	autocomplete={autocomplete as HTMLInputElement['autocomplete']}
	{inputmode}
	{spellcheck}
	aria-invalid={invalid || undefined}
	aria-describedby={describedBy}
	class="{baseClass} {invalid
		? 'border-[var(--color-primary)] focus:border-[var(--color-primary)] focus:ring-[var(--color-primary)]'
		: ''} {className}"
	oninput={oninput}
/>

// components/ui/input.tsx
import type { InputHTMLAttributes } from "react";

const variants = {
  auth: "w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-hover)] px-4 py-2.5 text-[var(--color-text)] placeholder-[var(--color-muted)] transition-colors focus:border-[var(--color-ring)] focus:outline-none focus:ring-1 focus:ring-[var(--color-ring)]",
  authPassword:
    "w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-hover)] py-2.5 pl-4 pr-10 text-[var(--color-text)] placeholder-[var(--color-muted)] transition-colors focus:border-[var(--color-ring)] focus:outline-none focus:ring-1 focus:ring-[var(--color-ring)]",
  app: "w-full border border-[var(--color-muted)]/40 bg-[var(--color-bg)] px-2 py-1 text-[var(--color-text)] focus:border-[var(--color-ring)] focus:outline-none focus:ring-1 focus:ring-[var(--color-ring)]",
  search:
    "block w-full rounded-md border border-[var(--color-border)] bg-[var(--color-surface-hover)] py-1.5 pl-10 pr-3 text-sm text-[var(--color-text)] placeholder-[var(--color-muted)] focus:border-[var(--color-primary)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]",
} as const;

export type InputVariant = keyof typeof variants;

type Props = InputHTMLAttributes<HTMLInputElement> & {
  variant?: InputVariant;
};

export function Input({ variant = "app", className = "", ...props }: Props) {
  return (
    <input
      className={`${variants[variant]} ${className}`.trim()}
      {...props}
    />
  );
}
