// src/lib/components/onboarding/OnboardingStepper.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Pencil from '@lucide/svelte/icons/pencil';
	import Trash2 from '@lucide/svelte/icons/trash-2';
	import type { OnboardingState, OnboardingStep } from '$lib/auth/session';
	import Button from '$lib/components/ui/Button.svelte';
	import ConfirmDialog from '$lib/components/ui/ConfirmDialog.svelte';
	import FormField from '$lib/components/ui/FormField.svelte';
	import Input from '$lib/components/ui/Input.svelte';
	import type { Locale } from '$lib/i18n/config';
	import { getDictionary } from '$lib/i18n/dictionaries';
	import type { OnboardingActionState } from '$lib/server/onboarding/actions';
	import { LIMITS } from '$lib/validation/schemas';

	type PlanRow = { id: string; name: string; price: number; duration_days: number };

	type Props = {
		locale: Locale;
		onboardingState: OnboardingState;
		plans: PlanRow[];
		showError?: boolean;
		form: OnboardingActionState;
	};

	let { locale, onboardingState, plans, showError = false, form }: Props = $props();

	const d = getDictionary(locale);
	const maxStep = $derived(onboardingState.step);
	let viewStep = $state(onboardingState.step as OnboardingStep);
	let prevMaxStep = $state(onboardingState.step);

	$effect(() => {
		if (maxStep !== prevMaxStep) {
			prevMaxStep = maxStep;
			viewStep = maxStep;
		}
	});

	function goBack() {
		viewStep = viewStep > 1 ? ((viewStep - 1) as OnboardingStep) : viewStep;
	}

	let profilePending = $state(false);
	let gymPending = $state(false);
	let addPlanPending = $state(false);
	let editPlanPending = $state(false);
	let editingId = $state(null as string | null);
	let deleting = $state(null as PlanRow | null);
</script>

<div class="flex w-full flex-col gap-8">
	<nav aria-label={d.onboarding.stepsLabel} class="flex gap-2">
		{#each [1, 2, 3, 4] as n (n)}
			{@const active = viewStep === n}
			{@const reached = maxStep >= n}
			<button
				type="button"
				disabled={!reached}
				onclick={() => (viewStep = n as OnboardingStep)}
				class="flex flex-1 flex-col gap-1 text-left {active
					? 'opacity-100'
					: reached
						? 'opacity-70'
						: 'opacity-40'} {reached ? 'cursor-pointer' : 'cursor-default'}"
			>
				<div
					class="h-1 rounded-full {reached
						? 'bg-[var(--color-primary)]'
						: 'bg-[var(--color-muted)]/30'}"
				></div>
				<span class="text-[10px] font-semibold uppercase tracking-wider text-[var(--color-muted)]">
					{n === 1
						? d.onboarding.stepYou
						: n === 2
							? d.onboarding.stepGym
							: n === 3
								? d.onboarding.stepPlans
								: d.onboarding.stepDone}
				</span>
			</button>
		{/each}
	</nav>

	{#if showError}
		<p
			class="rounded-lg border border-[var(--color-primary)]/20 bg-[var(--color-primary)]/10 p-3 text-sm font-medium text-[var(--color-primary)]"
		>
			{d.onboarding.errorSave}
		</p>
	{/if}

	<div class="flex flex-col gap-3">
		{#if viewStep === 1}
			<section class="flex flex-col gap-4">
				<div>
					<h2 class="text-xl font-bold text-[var(--color-text)]">{d.onboarding.profileTitle}</h2>
					<p class="mt-1 text-sm text-[var(--color-muted)]">{d.onboarding.profileSubtitle}</p>
					{#if onboardingState.organizationName}
						<p class="mt-2 text-xs text-[var(--color-muted)]">
							{d.onboarding.orgLabel}:
							<span class="font-medium text-[var(--color-text)]">{onboardingState.organizationName}</span>
						</p>
					{/if}
				</div>

				<form
					method="POST"
					action="?/saveProfile"
					class="flex flex-col gap-4"
					novalidate
					use:enhance={() => {
						profilePending = true;
						return async ({ update }) => {
							profilePending = false;
							await update();
						};
					}}
				>
					<input type="hidden" name="locale" value={locale} />
					<FormField label={d.onboarding.fullName} htmlFor="fullName" error={form?.fieldErrors?.fullName}>
						{#snippet children({ invalid, describedBy })}
							<Input
								id="fullName"
								required
								name="fullName"
								value={onboardingState.fullName ?? ''}
								placeholder={d.onboarding.fullNamePlaceholder}
								autocomplete="name"
								maxlength={LIMITS.personName}
								{invalid}
								{describedBy}
							/>
						{/snippet}
					</FormField>

					<fieldset class="flex flex-col gap-2">
						<legend class="mb-1 text-sm font-medium text-[var(--color-text)]">
							{d.onboarding.roleLegend}
						</legend>
						<div class="grid grid-cols-1 gap-1 sm:grid-cols-2">
							<label
								class="group relative cursor-pointer rounded-lg px-3 py-3 transition-colors hover:bg-[var(--color-surface-hover)] has-[:checked]:bg-[var(--color-primary-soft)]"
							>
								<input
									type="radio"
									name="roleIntent"
									value="owner"
									checked={!onboardingState.pendingAsProvisional}
									class="sr-only"
								/>
								<span class="flex flex-col gap-0.5">
									<span
										class="text-sm font-semibold text-[var(--color-text)] group-has-[:checked]:text-[var(--color-primary)]"
									>
										{d.onboarding.roleOwner}
									</span>
									<span class="text-xs leading-snug text-[var(--color-muted)]">
										{d.onboarding.roleOwnerHint}
									</span>
								</span>
							</label>
							<label
								class="group relative cursor-pointer rounded-lg px-3 py-3 transition-colors hover:bg-[var(--color-surface-hover)] has-[:checked]:bg-[var(--color-primary-soft)]"
							>
								<input
									type="radio"
									name="roleIntent"
									value="manager"
									checked={onboardingState.pendingAsProvisional}
									class="sr-only"
								/>
								<span class="flex flex-col gap-0.5">
									<span
										class="text-sm font-semibold text-[var(--color-text)] group-has-[:checked]:text-[var(--color-primary)]"
									>
										{d.onboarding.roleManager}
									</span>
									<span class="text-xs leading-snug text-[var(--color-muted)]">
										{d.onboarding.roleManagerHint}
									</span>
								</span>
							</label>
						</div>
					</fieldset>

					{#if form?.error}
						<p class="text-sm font-medium text-[var(--color-primary)]">{form.error}</p>
					{/if}

					<Button type="submit" variant="primaryBlock" disabled={profilePending}>
						{profilePending ? d.onboarding.saving : d.onboarding.continue}
					</Button>
				</form>
			</section>
		{:else if viewStep === 2}
			<section class="flex flex-col gap-4">
				<div>
					<h2 class="text-xl font-bold text-[var(--color-text)]">{d.onboarding.gymTitle}</h2>
					<p class="mt-1 text-sm text-[var(--color-muted)]">{d.onboarding.gymSubtitle}</p>
				</div>

				<form
					method="POST"
					action="?/saveGym"
					class="flex flex-col gap-4"
					novalidate
					use:enhance={() => {
						gymPending = true;
						return async ({ update }) => {
							gymPending = false;
							await update();
						};
					}}
				>
					<input type="hidden" name="locale" value={locale} />
					<FormField
						label={d.onboarding.gymName}
						htmlFor="gymName"
						hint={d.onboarding.gymNameHint}
						error={form?.fieldErrors?.gymName}
					>
						{#snippet children({ invalid, describedBy })}
							<Input
								id="gymName"
								required
								name="gymName"
								value={onboardingState.gymName ?? onboardingState.organizationName ?? ''}
								placeholder={d.onboarding.gymNamePlaceholder}
								maxlength={LIMITS.entityName}
								{invalid}
								{describedBy}
							/>
						{/snippet}
					</FormField>
					<FormField
						label={d.onboarding.gymAddress}
						htmlFor="gymAddress"
						hint={d.onboarding.gymAddressHint}
						error={form?.fieldErrors?.gymAddress}
					>
						{#snippet children({ invalid, describedBy })}
							<Input
								id="gymAddress"
								name="gymAddress"
								placeholder={d.onboarding.gymAddressPlaceholder}
								autocomplete="street-address"
								maxlength={LIMITS.address}
								{invalid}
								{describedBy}
							/>
						{/snippet}
					</FormField>
					<FormField
						label={d.onboarding.branchName}
						htmlFor="branchName"
						hint={d.onboarding.branchNameHint}
						error={form?.fieldErrors?.branchName}
					>
						{#snippet children({ invalid, describedBy })}
							<Input
								id="branchName"
								name="branchName"
								placeholder={d.onboarding.branchNamePlaceholder}
								maxlength={LIMITS.entityName}
								{invalid}
								{describedBy}
							/>
						{/snippet}
					</FormField>
					<FormField
						label={d.onboarding.branchAddress}
						htmlFor="branchAddress"
						hint={d.onboarding.branchAddressHint}
						error={form?.fieldErrors?.branchAddress}
					>
						{#snippet children({ invalid, describedBy })}
							<Input
								id="branchAddress"
								name="branchAddress"
								placeholder={d.onboarding.branchAddressPlaceholder}
								autocomplete="street-address"
								maxlength={LIMITS.address}
								{invalid}
								{describedBy}
							/>
						{/snippet}
					</FormField>

					{#if form?.error}
						<p class="text-sm font-medium text-[var(--color-primary)]">{form.error}</p>
					{/if}

					<Button type="submit" variant="primaryBlock" disabled={gymPending}>
						{gymPending ? d.onboarding.saving : d.onboarding.continue}
					</Button>
				</form>
			</section>
		{:else if viewStep === 3}
			{@const atLimit = plans.length >= 2}
			<section class="flex flex-col gap-4">
				<div>
					<h2 class="text-xl font-bold text-[var(--color-text)]">{d.onboarding.plansTitle}</h2>
					<p class="mt-1 text-sm text-[var(--color-muted)]">{d.onboarding.plansSubtitle}</p>
					<p
						class="mt-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-xs leading-relaxed text-[var(--color-muted)]"
					>
						{d.onboarding.plansExample}
					</p>
					{#if onboardingState.gymName}
						<p class="mt-2 text-xs text-[var(--color-muted)]">
							{d.onboarding.gymLabel}:
							<span class="font-medium text-[var(--color-text)]">{onboardingState.gymName}</span>
						</p>
					{/if}
				</div>

				{#if plans.length > 0}
					<ul class="space-y-2 text-sm">
						{#each plans as p (p.id)}
							<li class="rounded-lg border border-[var(--color-border)] px-3 py-2">
								{#if editingId === p.id}
									<form
										method="POST"
										action="?/updatePlan"
										class="flex flex-col gap-3"
										novalidate
										use:enhance={() => {
											editPlanPending = true;
											return async ({ update }) => {
												editPlanPending = false;
												editingId = null;
												await update();
											};
										}}
									>
										<input type="hidden" name="locale" value={locale} />
										<input type="hidden" name="plan_id" value={p.id} />
										<FormField label={d.plans.planName} htmlFor="edit-name-{p.id}" error={form?.fieldErrors?.name}>
											{#snippet children({ invalid, describedBy })}
												<Input
													id="edit-name-{p.id}"
													required
													name="name"
													value={p.name}
													maxlength={LIMITS.entityName}
													{invalid}
													{describedBy}
												/>
											{/snippet}
										</FormField>
										<div class="grid grid-cols-2 gap-3">
											<FormField label={d.plans.price} htmlFor="edit-price-{p.id}" error={form?.fieldErrors?.price}>
												{#snippet children({ invalid, describedBy })}
													<Input
														id="edit-price-{p.id}"
														required
														name="price"
														type="number"
														min={0}
														max={1_000_000}
														step="0.01"
														inputmode="decimal"
														value={String(p.price)}
														{invalid}
														{describedBy}
													/>
												{/snippet}
											</FormField>
											<FormField
												label={d.plans.durationDays}
												htmlFor="edit-days-{p.id}"
												error={form?.fieldErrors?.duration_days}
											>
												{#snippet children({ invalid, describedBy })}
													<Input
														id="edit-days-{p.id}"
														required
														name="duration_days"
														type="number"
														min={1}
														max={3650}
														step={1}
														inputmode="numeric"
														value={String(p.duration_days)}
														{invalid}
														{describedBy}
													/>
												{/snippet}
											</FormField>
										</div>
										{#if form?.error}
											<p class="text-sm font-medium text-[var(--color-primary)]">{form.error}</p>
										{/if}
										<div class="flex gap-2">
											<Button type="submit" class="flex-1" disabled={editPlanPending}>
												{editPlanPending ? d.onboarding.saving : d.plans.save}
											</Button>
											<Button type="button" variant="ghost" class="flex-1" onclick={() => (editingId = null)}>
												{d.plans.cancel}
											</Button>
										</div>
									</form>
								{:else}
									<div class="flex items-center justify-between gap-2">
										<div class="min-w-0">
											<p class="truncate font-medium text-[var(--color-text)]">{p.name}</p>
											<p class="text-[var(--color-muted)]">${p.price} · {p.duration_days}d</p>
										</div>
										<div class="flex shrink-0 items-center gap-1">
											<button
												type="button"
												onclick={() => (editingId = p.id)}
												class="inline-flex h-8 w-8 items-center justify-center rounded-md text-[var(--color-muted)] transition-colors hover:bg-[var(--color-surface-hover)] hover:text-[var(--color-text)]"
												aria-label={d.plans.edit}
												title={d.plans.edit}
											>
												<Pencil class="h-3.5 w-3.5" aria-hidden="true" />
											</button>
											<button
												type="button"
												onclick={() => (deleting = p)}
												class="inline-flex h-8 w-8 items-center justify-center rounded-md text-[var(--color-muted)] transition-colors hover:bg-[var(--color-surface-hover)] hover:text-[var(--color-primary)]"
												aria-label={d.plans.delete}
												title={d.plans.delete}
											>
												<Trash2 class="h-3.5 w-3.5" aria-hidden="true" />
											</button>
										</div>
									</div>
								{/if}
							</li>
						{/each}
					</ul>
				{/if}

				<ConfirmDialog
					open={deleting != null}
					title={d.plans.delete}
					description={deleting ? `${d.plans.delete}: ${deleting.name}` : undefined}
					cancelLabel={d.plans.cancel}
					confirmLabel={d.plans.delete}
					action="?/deletePlan"
					onclose={() => (deleting = null)}
				>
					{#if deleting}
						<input type="hidden" name="locale" value={locale} />
						<input type="hidden" name="plan_id" value={deleting.id} />
					{/if}
				</ConfirmDialog>

				{#if !atLimit}
					<form
						method="POST"
						action="?/addPlan"
						class="flex flex-col gap-3"
						novalidate
						use:enhance={() => {
							addPlanPending = true;
							return async ({ update }) => {
								addPlanPending = false;
								await update();
							};
						}}
					>
						<input type="hidden" name="locale" value={locale} />
						<FormField
							label={d.plans.planName}
							htmlFor="plan-name"
							hint={d.onboarding.planNameHint}
							error={form?.fieldErrors?.name}
						>
							{#snippet children({ invalid, describedBy })}
								<Input
									id="plan-name"
									required
									name="name"
									placeholder={d.onboarding.planNamePlaceholder}
									maxlength={LIMITS.entityName}
									{invalid}
									{describedBy}
								/>
							{/snippet}
						</FormField>
						<div class="grid grid-cols-2 gap-3">
							<FormField
								label={d.plans.price}
								htmlFor="plan-price"
								hint={d.onboarding.planPriceHint}
								error={form?.fieldErrors?.price}
							>
								{#snippet children({ invalid, describedBy })}
									<Input
										id="plan-price"
										required
										name="price"
										type="number"
										min={0}
										max={1_000_000}
										step="0.01"
										inputmode="decimal"
										placeholder="500"
										{invalid}
										{describedBy}
									/>
								{/snippet}
							</FormField>
							<FormField
								label={d.plans.durationDays}
								htmlFor="plan-days"
								hint={d.onboarding.planDurationHint}
								error={form?.fieldErrors?.duration_days}
							>
								{#snippet children({ invalid, describedBy })}
									<Input
										id="plan-days"
										required
										name="duration_days"
										type="number"
										min={1}
										max={3650}
										step={1}
										value="30"
										inputmode="numeric"
										{invalid}
										{describedBy}
									/>
								{/snippet}
							</FormField>
						</div>
						{#if form?.error}
							<p class="text-sm font-medium text-[var(--color-primary)]">{form.error}</p>
						{/if}
						<Button type="submit" variant="primaryBlock" disabled={addPlanPending}>
							{addPlanPending ? d.onboarding.saving : d.onboarding.addPlan}
						</Button>
					</form>
				{:else}
					<p class="text-sm text-[var(--color-muted)]">{d.onboarding.planLimit}</p>
				{/if}

				<form method="POST" action="?/skipPlans">
					<input type="hidden" name="locale" value={locale} />
					<Button
						type="submit"
						variant={plans.length > 0 ? 'primaryBlock' : 'ghost'}
						class={plans.length > 0 ? undefined : 'w-full py-2 text-sm'}
					>
						{plans.length > 0 ? d.onboarding.continue : d.onboarding.skipPlans}
					</Button>
				</form>
			</section>
		{:else if viewStep === 4}
			<section class="flex flex-col gap-4 text-center">
				<div>
					<h2 class="text-xl font-bold text-[var(--color-text)]">{d.onboarding.doneTitle}</h2>
					<p class="mt-2 text-sm text-[var(--color-muted)]">{d.onboarding.doneSubtitle}</p>
				</div>
				<dl class="space-y-2 rounded-lg border border-[var(--color-border)] p-4 text-left text-sm">
					<div class="flex justify-between gap-4">
						<dt class="text-[var(--color-muted)]">{d.onboarding.orgLabel}</dt>
						<dd class="font-medium text-[var(--color-text)]">{onboardingState.organizationName}</dd>
					</div>
					<div class="flex justify-between gap-4">
						<dt class="text-[var(--color-muted)]">{d.onboarding.gymLabel}</dt>
						<dd class="font-medium text-[var(--color-text)]">{onboardingState.gymName}</dd>
					</div>
				</dl>
				<form method="POST" action="?/finish">
					<input type="hidden" name="locale" value={locale} />
					<Button type="submit" variant="primaryBlock">{d.onboarding.goDashboard}</Button>
				</form>
			</section>
		{/if}

		{#if viewStep > 1}
			<Button type="button" variant="ghost" class="w-full py-2 text-sm" onclick={goBack}>
				{d.common.back}
			</Button>
		{/if}
	</div>
</div>

// app/[locale]/(auth)/onboarding/onboarding-stepper.tsx
"use client";

import { useActionState, useId, useState } from "react";
import { Pencil, Trash2 } from "lucide-react";
import type { Locale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";
import type { OnboardingState, OnboardingStep } from "@/lib/auth/session";
import {
  addOnboardingPlanAction,
  deleteOnboardingPlanAction,
  finishOnboardingAction,
  saveOnboardingGymAction,
  saveOnboardingProfileAction,
  skipOnboardingPlansAction,
  updateOnboardingPlanAction,
  type OnboardingActionState,
} from "./actions";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/confirm-dialog";
import { LIMITS } from "@/lib/validation/schemas";

type PlanRow = { id: string; name: string; price: number; duration_days: number };

type Props = {
  locale: Locale;
  state: OnboardingState;
  plans: PlanRow[];
  showError?: boolean;
};

export function OnboardingStepper({ locale, state, plans, showError }: Props) {
  const d = getDictionary(locale);
  const maxStep = state.step;
  const [viewStep, setViewStep] = useState<OnboardingStep>(maxStep);
  const [prevMaxStep, setPrevMaxStep] = useState(maxStep);

  if (maxStep !== prevMaxStep) {
    setPrevMaxStep(maxStep);
    setViewStep(maxStep);
  }

  function goBack() {
    setViewStep((current) => (current > 1 ? ((current - 1) as OnboardingStep) : current));
  }

  return (
    <div className="flex w-full flex-col gap-8">
      <nav aria-label={d.onboarding.stepsLabel} className="flex gap-2">
        {([1, 2, 3, 4] as const).map((n) => {
          const active = viewStep === n;
          const reached = maxStep >= n;
          return (
            <button
              key={n}
              type="button"
              disabled={!reached}
              onClick={() => setViewStep(n)}
              className={`flex flex-1 flex-col gap-1 text-left ${active ? "opacity-100" : reached ? "opacity-70" : "opacity-40"} ${reached ? "cursor-pointer" : "cursor-default"}`}
            >
              <div
                className={`h-1 rounded-full ${reached
                  ? "bg-[var(--color-primary)]"
                  : "bg-[var(--color-muted)]/30"
                  }`}
              />
              <span className="text-[10px] font-semibold uppercase tracking-wider text-[var(--color-muted)]">
                {n === 1
                  ? d.onboarding.stepYou
                  : n === 2
                    ? d.onboarding.stepGym
                    : n === 3
                      ? d.onboarding.stepPlans
                      : d.onboarding.stepDone}
              </span>
            </button>
          );
        })}
      </nav>

      {showError ? (
        <p className="rounded-lg border border-[var(--color-primary)]/20 bg-[var(--color-primary)]/10 p-3 text-sm font-medium text-[var(--color-primary)]">
          {d.onboarding.errorSave}
        </p>
      ) : null}

      <div className="flex flex-col gap-3">
        {viewStep === 1 ? <StepProfile locale={locale} state={state} /> : null}
        {viewStep === 2 ? <StepGym locale={locale} state={state} /> : null}
        {viewStep === 3 ? (
          <StepPlans locale={locale} state={state} plans={plans} />
        ) : null}
        {viewStep === 4 ? <StepDone locale={locale} state={state} /> : null}

        {viewStep > 1 ? (
          <Button
            type="button"
            variant="ghost"
            className="w-full py-2 text-sm"
            onClick={goBack}
          >
            {d.common.back}
          </Button>
        ) : null}
      </div>
    </div>
  );
}

function StepProfile({
  locale,
  state,
}: {
  locale: Locale;
  state: OnboardingState;
}) {
  const d = getDictionary(locale);
  const [formState, formAction, pending] = useActionState(
    saveOnboardingProfileAction,
    null as OnboardingActionState,
  );
  const nameId = useId();

  return (
    <section className="flex flex-col gap-4">
      <div>
        <h2 className="text-xl font-bold text-[var(--color-text)]">
          {d.onboarding.profileTitle}
        </h2>
        <p className="mt-1 text-sm text-[var(--color-muted)]">
          {d.onboarding.profileSubtitle}
        </p>
        {state.organizationName ? (
          <p className="mt-2 text-xs text-[var(--color-muted)]">
            {d.onboarding.orgLabel}:{" "}
            <span className="font-medium text-[var(--color-text)]">
              {state.organizationName}
            </span>
          </p>
        ) : null}
      </div>

      <form action={formAction} className="flex flex-col gap-4" noValidate>
        <input type="hidden" name="locale" value={locale} />
        <FormField
          label={d.onboarding.fullName}
          htmlFor={nameId}
          variant="auth"
          error={formState?.fieldErrors?.fullName}
        >
          <Input
            id={nameId}
            required
            name="fullName"
            variant="auth"
            defaultValue={state.fullName ?? ""}
            placeholder={d.onboarding.fullNamePlaceholder}
            autoComplete="name"
            maxLength={LIMITS.personName}
          />
        </FormField>

        <fieldset className="flex flex-col gap-2">
          <legend className="mb-1 text-sm font-medium text-[var(--color-text)]">
            {d.onboarding.roleLegend}
          </legend>
          <div className="grid grid-cols-1 gap-1 sm:grid-cols-2">
            <label className="group relative cursor-pointer rounded-lg px-3 py-3 transition-colors hover:bg-[var(--color-surface-hover)] has-[:checked]:bg-[var(--color-primary-soft)] has-[:checked]:hover:bg-[var(--color-primary-soft)]">
              <input
                type="radio"
                name="roleIntent"
                value="owner"
                defaultChecked={!state.pendingAsProvisional}
                className="sr-only"
              />
              <span className="flex flex-col gap-0.5">
                <span className="text-sm font-semibold text-[var(--color-text)] group-has-[:checked]:text-[var(--color-primary)]">
                  {d.onboarding.roleOwner}
                </span>
                <span className="text-xs leading-snug text-[var(--color-muted)]">
                  {d.onboarding.roleOwnerHint}
                </span>
              </span>
              <span
                aria-hidden
                className="pointer-events-none absolute inset-x-3 bottom-0 h-0.5 origin-left scale-x-0 bg-[var(--color-primary)] transition-transform group-has-[:checked]:scale-x-100"
              />
            </label>
            <label className="group relative cursor-pointer rounded-lg px-3 py-3 transition-colors hover:bg-[var(--color-surface-hover)] has-[:checked]:bg-[var(--color-primary-soft)] has-[:checked]:hover:bg-[var(--color-primary-soft)]">
              <input
                type="radio"
                name="roleIntent"
                value="manager"
                defaultChecked={state.pendingAsProvisional}
                className="sr-only"
              />
              <span className="flex flex-col gap-0.5">
                <span className="text-sm font-semibold text-[var(--color-text)] group-has-[:checked]:text-[var(--color-primary)]">
                  {d.onboarding.roleManager}
                </span>
                <span className="text-xs leading-snug text-[var(--color-muted)]">
                  {d.onboarding.roleManagerHint}
                </span>
              </span>
              <span
                aria-hidden
                className="pointer-events-none absolute inset-x-3 bottom-0 h-0.5 origin-left scale-x-0 bg-[var(--color-primary)] transition-transform group-has-[:checked]:scale-x-100"
              />
            </label>
          </div>
        </fieldset>

        {formState?.error ? (
          <p className="text-sm font-medium text-[var(--color-primary)]">
            {formState.error}
          </p>
        ) : null}

        <Button type="submit" variant="primaryBlock" disabled={pending}>
          {pending ? d.onboarding.saving : d.onboarding.continue}
        </Button>
      </form>
    </section>
  );
}

function StepGym({
  locale,
  state,
}: {
  locale: Locale;
  state: OnboardingState;
}) {
  const d = getDictionary(locale);
  const [formState, formAction, pending] = useActionState(
    saveOnboardingGymAction,
    null as OnboardingActionState,
  );
  const gymId = useId();
  const gymAddressId = useId();
  const branchId = useId();
  const branchAddressId = useId();

  return (
    <section className="flex flex-col gap-4">
      <div>
        <h2 className="text-xl font-bold text-[var(--color-text)]">
          {d.onboarding.gymTitle}
        </h2>
        <p className="mt-1 text-sm text-[var(--color-muted)]">
          {d.onboarding.gymSubtitle}
        </p>
      </div>

      <form action={formAction} className="flex flex-col gap-4" noValidate>
        <input type="hidden" name="locale" value={locale} />
        <FormField
          label={d.onboarding.gymName}
          htmlFor={gymId}
          variant="auth"
          hint={d.onboarding.gymNameHint}
          error={formState?.fieldErrors?.gymName}
        >
          <Input
            id={gymId}
            required
            name="gymName"
            variant="auth"
            defaultValue={state.gymName ?? state.organizationName ?? ""}
            placeholder={d.onboarding.gymNamePlaceholder}
            maxLength={LIMITS.entityName}
          />
        </FormField>
        <FormField
          label={d.onboarding.gymAddress}
          htmlFor={gymAddressId}
          variant="auth"
          hint={d.onboarding.gymAddressHint}
          error={formState?.fieldErrors?.gymAddress}
        >
          <Input
            id={gymAddressId}
            name="gymAddress"
            variant="auth"
            placeholder={d.onboarding.gymAddressPlaceholder}
            autoComplete="street-address"
            maxLength={LIMITS.address}
          />
        </FormField>
        <FormField
          label={d.onboarding.branchName}
          htmlFor={branchId}
          variant="auth"
          hint={d.onboarding.branchNameHint}
          error={formState?.fieldErrors?.branchName}
        >
          <Input
            id={branchId}
            name="branchName"
            variant="auth"
            placeholder={d.onboarding.branchNamePlaceholder}
            maxLength={LIMITS.entityName}
          />
        </FormField>
        <FormField
          label={d.onboarding.branchAddress}
          htmlFor={branchAddressId}
          variant="auth"
          hint={d.onboarding.branchAddressHint}
          error={formState?.fieldErrors?.branchAddress}
        >
          <Input
            id={branchAddressId}
            name="branchAddress"
            variant="auth"
            placeholder={d.onboarding.branchAddressPlaceholder}
            autoComplete="street-address"
            maxLength={LIMITS.address}
          />
        </FormField>

        {formState?.error ? (
          <p className="text-sm font-medium text-[var(--color-primary)]">
            {formState.error}
          </p>
        ) : null}

        <Button type="submit" variant="primaryBlock" disabled={pending}>
          {pending ? d.onboarding.saving : d.onboarding.continue}
        </Button>
      </form>
    </section>
  );
}

function StepPlans({
  locale,
  state,
  plans,
}: {
  locale: Locale;
  state: OnboardingState;
  plans: PlanRow[];
}) {
  const d = getDictionary(locale);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [deleting, setDeleting] = useState<PlanRow | null>(null);
  const [formState, formAction, pending] = useActionState(
    addOnboardingPlanAction,
    null as OnboardingActionState,
  );
  const [editState, editAction, editPending] = useActionState(
    updateOnboardingPlanAction,
    null as OnboardingActionState,
  );
  const nameId = useId();
  const priceId = useId();
  const daysId = useId();
  const editNameId = useId();
  const editPriceId = useId();
  const editDaysId = useId();
  const atLimit = plans.length >= 2;
  const editingPlan = plans.find((p) => p.id === editingId) ?? null;

  return (
    <section className="flex flex-col gap-4">
      <div>
        <h2 className="text-xl font-bold text-[var(--color-text)]">
          {d.onboarding.plansTitle}
        </h2>
        <p className="mt-1 text-sm text-[var(--color-muted)]">
          {d.onboarding.plansSubtitle}
        </p>
        <p className="mt-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-xs leading-relaxed text-[var(--color-muted)]">
          {d.onboarding.plansExample}
        </p>
        {state.gymName ? (
          <p className="mt-2 text-xs text-[var(--color-muted)]">
            {d.onboarding.gymLabel}:{" "}
            <span className="font-medium text-[var(--color-text)]">
              {state.gymName}
            </span>
          </p>
        ) : null}
      </div>

      {plans.length > 0 ? (
        <ul className="space-y-2 text-sm">
          {plans.map((p) => (
            <li
              key={p.id}
              className="rounded-lg border border-[var(--color-border)] px-3 py-2"
            >
              {editingPlan?.id === p.id ? (
                <form action={editAction} className="flex flex-col gap-3" noValidate>
                  <input type="hidden" name="locale" value={locale} />
                  <input type="hidden" name="plan_id" value={p.id} />
                  <FormField
                    label={d.plans.planName}
                    htmlFor={editNameId}
                    variant="auth"
                    error={editState?.fieldErrors?.name}
                  >
                    <Input
                      id={editNameId}
                      required
                      name="name"
                      variant="auth"
                      defaultValue={p.name}
                      maxLength={LIMITS.entityName}
                    />
                  </FormField>
                  <div className="grid grid-cols-2 gap-3">
                    <FormField
                      label={d.plans.price}
                      htmlFor={editPriceId}
                      variant="auth"
                      error={editState?.fieldErrors?.price}
                    >
                      <Input
                        id={editPriceId}
                        required
                        name="price"
                        type="number"
                        min={0}
                        max={1_000_000}
                        step="0.01"
                        inputMode="decimal"
                        variant="auth"
                        defaultValue={p.price}
                      />
                    </FormField>
                    <FormField
                      label={d.plans.durationDays}
                      htmlFor={editDaysId}
                      variant="auth"
                      error={editState?.fieldErrors?.duration_days}
                    >
                      <Input
                        id={editDaysId}
                        required
                        name="duration_days"
                        type="number"
                        min={1}
                        max={3650}
                        step={1}
                        inputMode="numeric"
                        variant="auth"
                        defaultValue={p.duration_days}
                      />
                    </FormField>
                  </div>
                  {editState?.error ? (
                    <p className="text-sm font-medium text-[var(--color-primary)]">
                      {editState.error}
                    </p>
                  ) : null}
                  <div className="flex gap-2">
                    <Button
                      type="submit"
                      variant="primary"
                      className="flex-1"
                      disabled={editPending}
                    >
                      {editPending ? d.onboarding.saving : d.plans.save}
                    </Button>
                    <Button
                      type="button"
                      variant="ghost"
                      className="flex-1"
                      onClick={() => setEditingId(null)}
                    >
                      {d.plans.cancel}
                    </Button>
                  </div>
                </form>
              ) : (
                <div className="flex items-center justify-between gap-2">
                  <div className="min-w-0">
                    <p className="truncate font-medium text-[var(--color-text)]">
                      {p.name}
                    </p>
                    <p className="text-[var(--color-muted)]">
                      ${p.price} · {p.duration_days}d
                    </p>
                  </div>
                  <div className="flex shrink-0 items-center gap-1">
                    <button
                      type="button"
                      onClick={() => setEditingId(p.id)}
                      className="inline-flex h-8 w-8 items-center justify-center rounded-md text-[var(--color-muted)] transition-colors hover:bg-[var(--color-surface-hover)] hover:text-[var(--color-text)]"
                      aria-label={d.plans.edit}
                      title={d.plans.edit}
                    >
                      <Pencil className="h-3.5 w-3.5" aria-hidden />
                    </button>
                    <button
                      type="button"
                      onClick={() => setDeleting(p)}
                      className="inline-flex h-8 w-8 items-center justify-center rounded-md text-[var(--color-muted)] transition-colors hover:bg-[var(--color-surface-hover)] hover:text-[var(--color-primary)]"
                      aria-label={d.plans.delete}
                      title={d.plans.delete}
                    >
                      <Trash2 className="h-3.5 w-3.5" aria-hidden />
                    </button>
                  </div>
                </div>
              )}
            </li>
          ))}
        </ul>
      ) : null}

      <ConfirmDialog
        open={deleting != null}
        onOpenChange={(open) => {
          if (!open) setDeleting(null);
        }}
        title={d.plans.delete}
        description={
          deleting ? `${d.plans.delete}: ${deleting.name}` : undefined
        }
        closeLabel={d.plans.cancel}
        cancelLabel={d.plans.cancel}
        confirmLabel={d.plans.delete}
        action={deleteOnboardingPlanAction}
      >
        {deleting ? (
          <>
            <input type="hidden" name="locale" value={locale} />
            <input type="hidden" name="plan_id" value={deleting.id} />
          </>
        ) : null}
      </ConfirmDialog>

      {!atLimit ? (
        <form action={formAction} className="flex flex-col gap-3" noValidate>
          <input type="hidden" name="locale" value={locale} />
          <FormField
            label={d.plans.planName}
            htmlFor={nameId}
            variant="auth"
            hint={d.onboarding.planNameHint}
            error={formState?.fieldErrors?.name}
          >
            <Input
              id={nameId}
              required
              name="name"
              variant="auth"
              placeholder={d.onboarding.planNamePlaceholder}
              maxLength={LIMITS.entityName}
            />
          </FormField>
          <div className="grid grid-cols-2 gap-3">
            <FormField
              label={d.plans.price}
              htmlFor={priceId}
              variant="auth"
              hint={d.onboarding.planPriceHint}
              error={formState?.fieldErrors?.price}
            >
              <Input
                id={priceId}
                required
                name="price"
                type="number"
                min={0}
                max={1_000_000}
                step="0.01"
                inputMode="decimal"
                variant="auth"
                placeholder="500"
              />
            </FormField>
            <FormField
              label={d.plans.durationDays}
              htmlFor={daysId}
              variant="auth"
              hint={d.onboarding.planDurationHint}
              error={formState?.fieldErrors?.duration_days}
            >
              <Input
                id={daysId}
                required
                name="duration_days"
                type="number"
                min={1}
                max={3650}
                step={1}
                defaultValue={30}
                inputMode="numeric"
                variant="auth"
              />
            </FormField>
          </div>
          {formState?.error ? (
            <p className="text-sm font-medium text-[var(--color-primary)]">
              {formState.error}
            </p>
          ) : null}
          <Button type="submit" variant="primaryBlock" disabled={pending}>
            {pending ? d.onboarding.saving : d.onboarding.addPlan}
          </Button>
        </form>
      ) : (
        <p className="text-sm text-[var(--color-muted)]">{d.onboarding.planLimit}</p>
      )}

      <form action={skipOnboardingPlansAction}>
        <input type="hidden" name="locale" value={locale} />
        <Button
          type="submit"
          variant={plans.length > 0 ? "primaryBlock" : "ghost"}
          className={plans.length > 0 ? undefined : "w-full py-2 text-sm"}
        >
          {plans.length > 0 ? d.onboarding.continue : d.onboarding.skipPlans}
        </Button>
      </form>
    </section>
  );
}

function StepDone({
  locale,
  state,
}: {
  locale: Locale;
  state: OnboardingState;
}) {
  const d = getDictionary(locale);

  return (
    <section className="flex flex-col gap-4 text-center">
      <div>
        <h2 className="text-xl font-bold text-[var(--color-text)]">
          {d.onboarding.doneTitle}
        </h2>
        <p className="mt-2 text-sm text-[var(--color-muted)]">
          {d.onboarding.doneSubtitle}
        </p>
      </div>
      <dl className="space-y-2 rounded-lg border border-[var(--color-border)] p-4 text-left text-sm">
        <div className="flex justify-between gap-4">
          <dt className="text-[var(--color-muted)]">{d.onboarding.orgLabel}</dt>
          <dd className="font-medium text-[var(--color-text)]">
            {state.organizationName}
          </dd>
        </div>
        <div className="flex justify-between gap-4">
          <dt className="text-[var(--color-muted)]">{d.onboarding.gymLabel}</dt>
          <dd className="font-medium text-[var(--color-text)]">{state.gymName}</dd>
        </div>
      </dl>
      <form action={finishOnboardingAction}>
        <input type="hidden" name="locale" value={locale} />
        <Button type="submit" variant="primaryBlock">
          {d.onboarding.goDashboard}
        </Button>
      </form>
    </section>
  );
}
