// src/routes/[locale]/onboarding/+page.svelte
<script lang="ts">
	import AmrapLogo from '$lib/components/landing/AmrapLogo.svelte';
	import LogoutButton from '$lib/components/LogoutButton.svelte';
	import OnboardingStepper from '$lib/components/onboarding/OnboardingStepper.svelte';
	import type { OnboardingActionState } from '$lib/server/onboarding/actions';

	let { data, form } = $props();
</script>

<svelte:head>
	<title>{data.d.onboarding.title} — AMRAP</title>
</svelte:head>

{#if data.orgError}
	<div class="auth-container flex min-h-screen flex-col items-center justify-center p-6">
		<div class="glass-panel flex w-full max-w-md flex-col items-center rounded-2xl p-8 text-center shadow-2xl sm:p-10">
			<AmrapLogo class="mb-6 h-12 w-auto" />
			<h1 class="text-xl font-bold text-[var(--color-text)]">{data.d.onboarding.title}</h1>
			<p class="mt-3 text-sm text-[var(--color-primary)]" role="alert">{data.d.onboarding.errorSave}</p>
			<a
				href="/auth/ensure-organization?locale={data.locale}"
				class="mt-6 text-sm font-semibold text-[var(--color-primary)] underline"
			>
				{data.d.common.back}
			</a>
			<LogoutButton
				locale={data.locale}
				class="mt-4 text-sm text-[var(--color-muted)] transition-colors hover:text-[var(--color-text)]"
			>
				{data.d.nav.logout}
			</LogoutButton>
		</div>
	</div>
{:else}
	<div class="auth-container flex min-h-screen flex-col items-center justify-center p-6">
		<div class="glass-panel animate-fade-in-up flex w-full max-w-lg flex-col rounded-2xl p-8 shadow-2xl sm:p-10">
			<div class="mb-8 flex flex-col items-center text-center">
				<div class="mb-5 flex w-full justify-center">
					<a href="/{data.locale}" aria-label="AMRAP">
						<AmrapLogo class="h-12 w-auto sm:h-14" />
					</a>
				</div>
				<h1 class="text-2xl font-bold tracking-tight text-[var(--color-text)]">
					{data.d.onboarding.title}
				</h1>
				<p class="mt-2 text-sm text-[var(--color-muted)]">{data.d.onboarding.subtitle}</p>
			</div>

			<OnboardingStepper
				locale={data.locale}
				onboardingState={data.state}
				plans={data.plans}
				showError={data.showError}
				form={(form as OnboardingActionState) ?? null}
			/>

			<div class="mt-8 border-t border-[var(--color-border)] pt-5 text-center">
				<LogoutButton
					locale={data.locale}
					class="text-sm text-[var(--color-muted)] transition-colors hover:text-[var(--color-text)]"
				>
					{data.d.nav.logout}
				</LogoutButton>
			</div>
		</div>
	</div>
{/if}

// app/[locale]/(auth)/onboarding/page.tsx
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import type { Locale } from "@/lib/i18n/config";
import { isLocale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";
import {
  getOnboardingState,
  getSessionUser,
  getWorkspace,
} from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { AmrapLogo } from "@/components/landing/amrap-logo";
import { LogoutButton } from "@/components/logout-button";
import { OnboardingStepper } from "./onboarding-stepper";

export default async function OnboardingPage({
  params,
  searchParams,
}: {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ error?: string }>;
}) {
  const { locale: raw } = await params;
  if (!isLocale(raw)) notFound();
  const locale = raw as Locale;
  const sp = await searchParams;
  const d = getDictionary(locale);

  const user = await getSessionUser();
  if (!user) redirect(`/${locale}/login`);

  const state = await getOnboardingState();
  if (!state) redirect(`/${locale}/login`);

  // Authenticated but org missing (e.g. confirm before RPC finished).
  // Org create + cookie clear must run in a Route Handler, not RSC render.
  if (!state.organizationId) {
    if (sp.error === "org") {
      return (
        <div className="auth-container flex min-h-screen flex-col items-center justify-center p-6">
          <div className="glass-panel flex w-full max-w-md flex-col items-center rounded-2xl p-8 text-center shadow-2xl sm:p-10">
            <AmrapLogo priority className="mb-6 h-12 w-auto" />
            <h1 className="text-xl font-bold text-[var(--color-text)]">
              {d.onboarding.title}
            </h1>
            <p className="mt-3 text-sm text-[var(--color-primary)]" role="alert">
              {d.onboarding.errorSave}
            </p>
            <Link
              href={`/auth/ensure-organization?locale=${locale}`}
              className="mt-6 text-sm font-semibold text-[var(--color-primary)] underline"
            >
              {d.common.back}
            </Link>
            <LogoutButton
              locale={locale}
              className="mt-4 text-sm text-[var(--color-muted)] transition-colors hover:text-[var(--color-text)]"
            >
              {d.nav.logout}
            </LogoutButton>
          </div>
        </div>
      );
    }
    redirect(`/auth/ensure-organization?locale=${locale}`);
  }

  const workspace = await getWorkspace();
  if (state.completed && workspace) {
    redirect(`/${locale}/dashboard`);
  }

  let plans: { id: string; name: string; price: number; duration_days: number }[] =
    [];
  if (state.gymId) {
    const supabase = await createClient();
    const { data } = await supabase
      .from("plans")
      .select("id, name, price, duration_days")
      .eq("gym_id", state.gymId)
      .order("created_at", { ascending: true })
      .limit(2);
    plans = (data ?? []).map((p) => ({
      id: p.id,
      name: p.name,
      price: Number(p.price),
      duration_days: p.duration_days,
    }));
  }

  return (
    <div className="auth-container flex min-h-screen flex-col items-center justify-center p-6">
      <div className="glass-panel animate-fade-in-up flex w-full max-w-lg flex-col rounded-2xl p-8 shadow-2xl sm:p-10">
        <div className="mb-8 flex flex-col items-center text-center">
          <div className="mb-5 flex w-full justify-center">
            <Link href={`/${locale}`} aria-label="AMRAP">
              <AmrapLogo priority className="h-12 w-auto sm:h-14" />
            </Link>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-[var(--color-text)]">
            {d.onboarding.title}
          </h1>
          <p className="mt-2 text-sm text-[var(--color-muted)]">
            {d.onboarding.subtitle}
          </p>
        </div>
        <OnboardingStepper
          locale={locale}
          state={state}
          plans={plans}
          showError={Boolean(sp.error)}
        />
        <div className="mt-8 border-t border-[var(--color-border)] pt-5 text-center">
          <LogoutButton
            locale={locale}
            className="text-sm text-[var(--color-muted)] transition-colors hover:text-[var(--color-text)]"
          >
            {d.nav.logout}
          </LogoutButton>
        </div>
      </div>
    </div>
  );
}
