// app/[locale]/(auth)/login/login-form.tsx
"use client";

import { useActionState, useId, useState } from "react";
import Link from "next/link";
import type { Locale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";
import { loginAction, type LoginState } from "./actions";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { PasswordInput } from "@/components/ui/password-input";
import { Button } from "@/components/ui/button";
import { LIMITS } from "@/lib/validation/schemas";

export function LoginForm({ locale }: { locale: Locale }) {
  const d = getDictionary(locale);
  const [state, formAction, pending] = useActionState(
    loginAction,
    null as LoginState,
  );
  const emailId = useId();
  const passwordId = useId();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const canSubmit = email.trim().length > 0 && password.length > 0;
  const fe = state?.fieldErrors;

  return (
    <div className="flex w-full flex-col gap-5">
      <form action={formAction} className="flex flex-col gap-4" noValidate>
        <input type="hidden" name="locale" value={locale} />
        <FormField
          label={d.login.email}
          htmlFor={emailId}
          variant="auth"
          error={fe?.email}
        >
          <Input
            id={emailId}
            required
            name="email"
            type="email"
            autoComplete="email"
            autoCapitalize="none"
            autoCorrect="off"
            spellCheck={false}
            inputMode="email"
            maxLength={LIMITS.email}
            variant="auth"
            placeholder={d.login.emailPlaceholder}
            value={email}
            onChange={(e) => setEmail(e.target.value.toLowerCase())}
          />
        </FormField>
        <FormField
          label={d.login.password}
          htmlFor={passwordId}
          variant="auth"
          error={fe?.password}
        >
          <PasswordInput
            id={passwordId}
            required
            name="password"
            autoComplete="current-password"
            maxLength={LIMITS.password.max}
            variant="auth"
            placeholder="••••••••"
            showLabel={d.login.showPassword}
            hideLabel={d.login.hidePassword}
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </FormField>
        {state?.error ? (
          <p className="text-sm font-medium text-[var(--color-primary)]" role="alert">
            {state.error}
          </p>
        ) : null}
        <Button
          type="submit"
          variant="primaryBlock"
          disabled={pending || !canSubmit}
        >
          {pending ? d.login.submitting : d.login.submit}
        </Button>
      </form>
      <div className="text-center">
        <p className="text-sm text-[var(--color-muted)]">
          {d.login.registerPrompt}{" "}
          <Link
            href={`/${locale}/register`}
            className="font-semibold text-[var(--color-text)] transition-colors hover:text-[var(--color-primary)]"
          >
            {d.login.registerLink}
          </Link>
        </p>
      </div>
    </div>
  );
}

// src/lib/components/auth/LoginForm.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { Locale } from '$lib/i18n/config';
	import type { Dictionary } from '$lib/i18n/dictionaries';
	import type { LoginState } from '$lib/server/auth/login';
	import FormField from '$lib/components/ui/FormField.svelte';
	import Input from '$lib/components/ui/Input.svelte';
	import PasswordInput from '$lib/components/ui/PasswordInput.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import {
		LIMITS,
		sanitizeEmailInput,
		sanitizePasswordInput
	} from '$lib/validation/schemas';

	type Props = {
		locale: Locale;
		d: Dictionary;
		form: LoginState;
	};

	let { locale, d, form }: Props = $props();

	let email = $state('');
	let password = $state('');
	let pending = $state(false);

	const emailId = 'login-email';
	const passwordId = 'login-password';
	const canSubmit = $derived(email.trim().length > 0 && password.length > 0);
	const fe = $derived(form?.fieldErrors);
</script>

<div class="flex w-full flex-col gap-5">
	<form
		method="POST"
		action="?/login"
		class="flex flex-col gap-4"
		novalidate
		use:enhance={() => {
			pending = true;
			return async ({ update }) => {
				pending = false;
				await update();
			};
		}}
	>
		<input type="hidden" name="locale" value={locale} />
		<FormField label={d.login.email} htmlFor={emailId} error={fe?.email}>
			{#snippet children({ invalid, describedBy })}
				<Input
					id={emailId}
					name="email"
					type="email"
					autocomplete="email"
					inputmode="email"
					spellcheck={false}
					required
					maxlength={LIMITS.email}
					placeholder={d.login.emailPlaceholder}
					bind:value={email}
					{invalid}
					{describedBy}
					oninput={(e) => {
						email = sanitizeEmailInput((e.currentTarget as HTMLInputElement).value);
					}}
				/>
			{/snippet}
		</FormField>

		<FormField label={d.login.password} htmlFor={passwordId} error={fe?.password}>
			{#snippet children({ invalid, describedBy })}
				<PasswordInput
					id={passwordId}
					name="password"
					autocomplete="current-password"
					maxlength={LIMITS.password.max}
					required
					showLabel={d.login.showPassword}
					hideLabel={d.login.hidePassword}
					bind:value={password}
					{invalid}
					{describedBy}
					oninput={(e) => {
						password = sanitizePasswordInput((e.currentTarget as HTMLInputElement).value);
					}}
				/>
			{/snippet}
		</FormField>

		{#if form?.error}
			<p class="text-sm font-medium text-[var(--color-primary)]" role="alert">{form.error}</p>
		{/if}

		<Button type="submit" variant="primaryBlock" disabled={pending || !canSubmit}>
			{pending ? d.login.submitting : d.login.submit}
		</Button>
	</form>

	<div class="text-center">
		<p class="text-sm text-[var(--color-muted)]">
			{d.login.registerPrompt}
			<a
				href="/{locale}/register"
				class="font-semibold text-[var(--color-text)] transition-colors hover:text-[var(--color-primary)]"
			>
				{d.login.registerLink}
			</a>
		</p>
	</div>
</div>
