// src/routes/[locale]/(ops)/members/+page.svelte
<script lang="ts">
	import UserPlus from '@lucide/svelte/icons/user-plus';
	import CreateMemberDialog from '$lib/components/members/CreateMemberDialog.svelte';
	import MembersList from '$lib/components/members/MembersList.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import type { CreateMemberState } from '$lib/server/members/actions';
	import type { PageProps } from './$types';

	let { data, form }: PageProps = $props();
	const d = $derived(data.d!);

	let createOpen = $state(false);
	let highlightId = $state<string | null>(null);
	let clearTimer: ReturnType<typeof setTimeout> | null = null;

	const formResult = $derived((form ?? null) as CreateMemberState);

	function flashRow(memberId: string) {
		if (clearTimer != null) clearTimeout(clearTimer);
		highlightId = memberId;
		clearTimer = setTimeout(() => {
			highlightId = null;
			clearTimer = null;
		}, 3000);
	}
</script>

<svelte:head>
	<title>{d.members.title} — AMRAP</title>
</svelte:head>

{#if data.forbidden}
	<p class="text-[var(--color-muted)]">{d.common.forbidden}</p>
{:else}
	<div class="mx-auto flex w-full max-w-6xl animate-fade-in-up flex-col gap-5">
		{#if data.listError}
			<p
				class="rounded-lg border border-[var(--color-primary)]/20 bg-[var(--color-primary)]/10 px-4 py-3 text-sm font-medium text-[var(--color-primary)]"
				role="alert"
			>
				{d.members.error}
			</p>
		{/if}

		<header class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
			<div>
				<h1 class="font-title text-3xl font-bold tracking-tight text-[var(--color-text)]">
					{d.members.title}
				</h1>
				<p class="mt-1 text-sm text-[var(--color-muted)]">{d.members.subtitle}</p>
			</div>
			<div class="flex flex-wrap items-center gap-2">
				<Button
					type="button"
					class="inline-flex min-h-11 items-center gap-2 shadow-sm"
					onclick={() => (createOpen = true)}
				>
					<UserPlus class="h-4 w-4" aria-hidden="true" />
					{d.members.newMember}
				</Button>
			</div>
		</header>

		<MembersList
			locale={data.locale}
			members={data.members}
			plans={data.plans}
			meta={data.meta}
			filters={data.filters}
			{highlightId}
			labels={{
				name: d.members.name,
				email: d.members.email,
				plan: d.members.plan,
				noPlan: d.members.noPlan,
				status: d.members.status,
				expires: d.members.expires,
				active: d.members.active,
				expired: d.members.expired,
				actions: d.members.actions,
				view: d.members.view,
				noMembers: d.members.noMembers,
				noResults: d.members.noResults,
				searchPlaceholder: d.members.searchPlaceholder,
				filterAll: d.members.filterAll,
				filterActive: d.members.filterActive,
				filterExpired: d.members.filterExpired,
				filterPlan: d.members.filterPlan,
				filterPlanAll: d.members.filterPlanAll,
				showing: d.members.showing,
				reload: d.members.reload,
				newBadge: d.members.newBadge,
				previous: d.common.previous,
				next: d.common.next,
				invitePending: d.inviteStatus.pending,
				inviteAccepted: d.inviteStatus.accepted,
				inviteCancelled: d.inviteStatus.cancelled
			}}
		/>
	</div>

	<CreateMemberDialog
		open={createOpen}
		onOpenChange={(open) => (createOpen = open)}
		locale={data.locale}
		{d}
		plans={data.activePlans}
		{formResult}
		onSuccess={flashRow}
	/>
{/if}

// app/[locale]/(app)/members/page.tsx
import { redirect, notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/auth/session";
import { canInWorkspace } from "@/lib/auth/permissions";
import type { Locale } from "@/lib/i18n/config";
import { isLocale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";
import { RegisterUserButton } from "@/components/register-user-dialog";
import { MembersClient } from "@/components/members-client";
import {
  MEMBERSHIP_LIST_SELECT,
  mapMembershipRow,
} from "@/lib/members/queries";

export default async function MembersPage({
  params,
  searchParams,
}: {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ error?: string }>;
}) {
  const { locale: raw } = await params;
  if (!isLocale(raw)) notFound();
  const locale = raw as Locale;
  const sp = await searchParams;

  const workspace = await getWorkspace();
  if (!workspace) redirect(`/${locale}/login`);
  if (!canInWorkspace(workspace, "manage_members")) {
    return (
      <p className="text-[var(--color-muted)]">{getDictionary(locale).common.forbidden}</p>
    );
  }

  const d = getDictionary(locale);
  const supabase = await createClient();
  const [{ data: rows }, { data: planRows }] = await Promise.all([
    supabase
      .from("memberships")
      .select(MEMBERSHIP_LIST_SELECT)
      .eq("gym_id", workspace.gymId)
      .order("created_at", { ascending: false }),
    supabase
      .from("plans")
      .select("id, name, price, duration_days, is_active")
      .eq("gym_id", workspace.gymId)
      .order("created_at", { ascending: false }),
  ]);

  const members = (rows ?? [])
    .map((r) => mapMembershipRow(r as Parameters<typeof mapMembershipRow>[0]))
    .filter((m): m is NonNullable<typeof m> => m != null);

  const plans = (planRows ?? []).map((p) => ({
    id: p.id,
    name: p.name,
    price: Number(p.price),
    duration_days: p.duration_days,
    is_active: p.is_active !== false,
  }));
  const activePlans = plans
    .filter((p) => p.is_active)
    .map(({ id, name, price, duration_days }) => ({
      id,
      name,
      price,
      duration_days,
    }));

  return (
    <div className="mx-auto flex w-full max-w-6xl flex-col gap-5">
      <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="font-title text-3xl font-bold tracking-tight text-[var(--color-text)]">
            {d.members.title}
          </h1>
          <p className="mt-1 text-sm text-[var(--color-muted)]">
            {d.members.subtitle}
          </p>
        </div>
        <RegisterUserButton
          locale={locale}
          canManageMembers
          canManageStaff={false}
          plans={activePlans}
          defaultRole="member"
          allowedRoles={["member"]}
          label={d.members.newMember}
        />
      </header>

      {sp.error ? (
        <p
          className="rounded-lg border border-[var(--color-primary)]/20 bg-[var(--color-primary)]/10 px-4 py-3 text-sm font-medium text-[var(--color-primary)]"
          role="alert"
        >
          {d.members.error}
        </p>
      ) : null}

      <MembersClient
        locale={locale}
        members={members}
        plans={plans.map((p) => ({ id: p.id, name: p.name }))}
        labels={{
          name: d.members.name,
          email: d.members.email,
          plan: d.members.plan,
          noPlan: d.members.noPlan,
          status: d.members.status,
          expires: d.members.expires,
          active: d.members.active,
          expired: d.members.expired,
          actions: d.members.actions,
          view: d.members.view,
          noMembers: d.members.noMembers,
          noResults: d.members.noResults,
          searchPlaceholder: d.members.searchPlaceholder,
          filterAll: d.members.filterAll,
          filterActive: d.members.filterActive,
          filterExpired: d.members.filterExpired,
          filterPlan: d.members.filterPlan,
          filterPlanAll: d.members.filterPlanAll,
          showing: d.members.showing,
        }}
      />
    </div>
  );
}
