// components/amrap-watermark.tsx
import Link from "next/link";
import { AmrapLogo } from "@/components/landing/amrap-logo";
import type { Locale } from "@/lib/i18n/config";

type Props = {
  locale: Locale;
  label: string;
};

/** Subtle Amrap brand mark pinned to the bottom of the app shell. */
export function AmrapWatermark({ locale, label }: Props) {
  return (
    <div className="flex shrink-0 items-center justify-center border-t border-[var(--color-border)]/60 bg-[var(--color-bg)] py-2.5">
      <Link
        href={`/${locale}`}
        className="inline-flex items-center gap-2 text-[var(--color-muted)] transition-opacity hover:opacity-80"
        aria-label="AMRAP"
      >
        <span className="text-[10px] font-medium uppercase tracking-[0.14em] text-[var(--color-muted)]/80">
          {label}
        </span>
        <AmrapLogo className="h-3.5 w-auto opacity-45" />
      </Link>
    </div>
  );
}

// src/lib/components/AmrapWatermark.svelte
<script lang="ts">
	import AmrapLogo from '$lib/components/landing/AmrapLogo.svelte';
	import type { Locale } from '$lib/i18n/config';

	type Props = {
		locale: Locale;
		label: string;
		class?: string;
	};

	let { locale, label, class: className = '' }: Props = $props();
</script>

<div
	class="flex items-center justify-center gap-2 border-t border-[var(--color-border)] px-4 py-2 {className}"
>
	<a
		href="/{locale}"
		class="inline-flex items-center gap-2 text-xs text-[var(--color-muted)] transition-colors hover:text-[var(--color-text)]"
	>
		<span>{label}</span>
		<AmrapLogo class="h-4 w-auto opacity-80" />
	</a>
</div>
