// amrap-next/components/register-user-dialog.tsx
"use client";

import {
  Plus,
  UserRound,
  Dumbbell,
  Users,
  type LucideIcon,
} from "lucide-react";
import {
  useActionState,
  useEffect,
  useEffectEvent,
  useId,
  useState,
  type ReactNode,
} from "react";
import {
  createMember,
  type CreateMemberState,
} from "@/app/[locale]/(app)/members/actions";
import {
  createStaffOrTrainer,
  type CreateTeamMemberState,
} from "@/app/[locale]/(app)/team/actions";
import { Dialog } from "@/components/ui/dialog";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { PhoneInput } from "@/components/ui/phone-input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import type { Locale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";
import { LIMITS, sanitizeEmailInput, sanitizePersonNameInput } from "@/lib/validation/schemas";

export type RegisterRole = "member" | "trainer" | "staff";

export type RegisterPlanOption = {
  id: string;
  name: string;
  price: number;
  duration_days: number;
};

export type RegisterSuccessPayload = {
  memberId?: string;
  teamMemberId?: string;
  role: RegisterRole;
};

type RegisterUserDialogProps = {
  locale: Locale;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  defaultRole?: RegisterRole;
  allowedRoles?: RegisterRole[];
  canManageMembers: boolean;
  canManageStaff: boolean;
  plans?: RegisterPlanOption[];
  onSuccess?: (payload: RegisterSuccessPayload) => void;
};

const ROLE_ICONS: Record<RegisterRole, LucideIcon> = {
  member: UserRound,
  trainer: Dumbbell,
  staff: Users,
};

function rolesForPermissions(
  canManageMembers: boolean,
  canManageStaff: boolean,
  allowedRoles?: RegisterRole[],
): RegisterRole[] {
  const base: RegisterRole[] = [];
  if (canManageMembers) base.push("member");
  if (canManageStaff) {
    base.push("trainer", "staff");
  }
  if (!allowedRoles) return base;
  return base.filter((r) => allowedRoles.includes(r));
}

function roleLabel(
  r: RegisterRole,
  d: ReturnType<typeof getDictionary>,
): string {
  if (r === "member") return d.registerUser.roleMember;
  if (r === "trainer") return d.registerUser.roleTrainer;
  return d.registerUser.roleStaff;
}

function formatPlanLabel(
  plan: RegisterPlanOption,
  template: string,
): string {
  const price =
    typeof plan.price === "number"
      ? plan.price.toFixed(2)
      : String(plan.price);
  const meta = template
    .replace("{days}", String(plan.duration_days))
    .replace("{price}", price);
  return `${plan.name} — ${meta}`;
}

type FormBodyProps = {
  locale: Locale;
  roles: RegisterRole[];
  initialRole: RegisterRole;
  plans?: RegisterPlanOption[];
  onOpenChange: (open: boolean) => void;
  onSuccess?: (payload: RegisterSuccessPayload) => void;
};

function RegisterUserFormBody({
  locale,
  roles,
  initialRole,
  plans: plansProp,
  onOpenChange,
  onSuccess,
}: FormBodyProps) {
  const plans = plansProp ?? [];
  const d = getDictionary(locale);
  const nameId = useId();
  const phoneId = useId();
  const emailId = useId();
  const planId = useId();
  const methodId = useId();
  const [role, setRole] = useState<RegisterRole>(initialRole);
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [email, setEmail] = useState("");
  const [selectedPlan, setSelectedPlan] = useState(plans[0]?.id ?? "");
  const [method, setMethod] = useState<"cash" | "transfer">("cash");

  const [memberState, memberAction, memberPending] = useActionState(
    createMember,
    null as CreateMemberState,
  );
  const [teamState, teamAction, teamPending] = useActionState(
    createStaffOrTrainer,
    null as CreateTeamMemberState,
  );

  const isMember = role === "member";
  const state = isMember ? memberState : teamState;
  const pending = isMember ? memberPending : teamPending;
  const fe = state?.fieldErrors;

  const onMemberSuccess = useEffectEvent(() => {
    if (!memberState?.success) return;
    onSuccess?.({
      role: "member",
      memberId: memberState.memberId,
    });
    if (!memberState.emailWarning) {
      onOpenChange(false);
    }
  });

  const onTeamSuccess = useEffectEvent(() => {
    if (!teamState?.success) return;
    onSuccess?.({
      role: teamState.role ?? "staff",
      teamMemberId: teamState.teamMemberId,
    });
    if (!teamState.emailWarning) {
      onOpenChange(false);
    }
  });

  useEffect(() => {
    if (!memberState?.success) return;
    onMemberSuccess();
  }, [memberState]);

  useEffect(() => {
    if (!teamState?.success) return;
    onTeamSuccess();
  }, [teamState]);

  const nameOk = name.trim().length > 0;
  const emailOk = email.trim().length > 0;
  const planOk = selectedPlan.length > 0;
  const canSubmit = isMember
    ? nameOk && emailOk && planOk && plans.length > 0 && !pending
    : nameOk && emailOk && !pending;

  const actions = (
    <div className="flex flex-row-reverse flex-wrap items-center gap-3 pt-1">
      <Button
        type="submit"
        variant="primary"
        className="min-w-[8.5rem] flex-1 sm:flex-none"
        disabled={!canSubmit}
      >
        {pending ? d.registerUser.submitting : d.registerUser.submit}
      </Button>
      <Button
        type="button"
        variant="ghost"
        className="min-w-[6rem] flex-1 px-4 py-2.5 sm:flex-none"
        onClick={() => onOpenChange(false)}
      >
        {d.registerUser.cancel}
      </Button>
    </div>
  );

  const errorBanner =
    state?.error && !state.success ? (
      <p
        className="rounded-lg border border-[var(--color-primary)]/20 bg-[var(--color-primary)]/10 p-3 text-sm font-medium text-[var(--color-primary)]"
        role="alert"
      >
        {state.error}
      </p>
    ) : null;

  const emailWarning =
    state && "emailWarning" in state && state.emailWarning ? (
      <p
        className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-hover)] p-3 text-sm text-[var(--color-muted)]"
        role="status"
      >
        {state.emailWarning}
      </p>
    ) : null;

  return (
    <div className="flex flex-col gap-5">
      <fieldset>
        <legend className="mb-2 text-sm font-medium text-[var(--color-text)]">
          {d.registerUser.roleLabel}
        </legend>
        <div
          role="radiogroup"
          aria-label={d.registerUser.roleLabel}
          className={`grid gap-1 rounded-xl bg-[var(--color-surface-hover)] p-1 ${
            roles.length === 1
              ? "grid-cols-1"
              : roles.length === 2
                ? "grid-cols-2"
                : "grid-cols-3"
          }`}
        >
          {roles.map((r) => {
            const selected = role === r;
            const Icon = ROLE_ICONS[r];
            return (
              <label
                key={r}
                className={`flex cursor-pointer flex-col items-center gap-1 rounded-lg px-2 py-2.5 text-center text-xs font-semibold transition-all sm:text-sm ${
                  selected
                    ? "bg-[var(--color-surface)] text-[var(--color-text)] shadow-sm ring-1 ring-[var(--color-border)]"
                    : "text-[var(--color-muted)] hover:text-[var(--color-text)]"
                }`}
              >
                <input
                  type="radio"
                  name="register-role"
                  value={r}
                  checked={selected}
                  onChange={() => setRole(r)}
                  className="sr-only"
                />
                <Icon
                  className={`h-4 w-4 ${
                    selected
                      ? "text-[var(--color-primary)]"
                      : "text-[var(--color-muted)]"
                  }`}
                  aria-hidden
                />
                {roleLabel(r, d)}
              </label>
            );
          })}
        </div>
      </fieldset>

      {isMember ? (
        plans.length === 0 ? (
          <div className="flex flex-col gap-4">
            <p
              className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-hover)] p-3 text-sm text-[var(--color-muted)]"
              role="status"
            >
              {d.registerUser.noPlans}
            </p>
            <button
              type="button"
              onClick={() => onOpenChange(false)}
              className="text-center text-sm text-[var(--color-muted)] transition-colors hover:text-[var(--color-text)]"
            >
              {d.registerUser.cancel}
            </button>
          </div>
        ) : (
          <form action={memberAction} className="flex flex-col gap-4" noValidate>
            <input type="hidden" name="locale" value={locale} />
            <div className="grid gap-4 sm:grid-cols-2">
              <FormField
                label={d.members.name}
                htmlFor={nameId}
                variant="auth"
                error={fe?.name}
              >
                <Input
                  id={nameId}
                  required
                  name="name"
                  variant="auth"
                  maxLength={LIMITS.personName}
                  autoComplete="name"
                  placeholder={d.registerUser.namePlaceholder}
                  value={name}
                  onChange={(e) => setName(sanitizePersonNameInput(e.target.value))}
                />
              </FormField>
              <FormField
                label={d.registerUser.email}
                htmlFor={emailId}
                variant="auth"
                error={fe?.email}
              >
                <Input
                  id={emailId}
                  required
                  type="email"
                  name="email"
                  variant="auth"
                  maxLength={LIMITS.email}
                  autoComplete="email"
                  autoCapitalize="none"
                  autoCorrect="off"
                  spellCheck={false}
                  inputMode="email"
                  placeholder={d.registerUser.emailPlaceholder}
                  value={email}
                  onChange={(e) => setEmail(sanitizeEmailInput(e.target.value))}
                />
              </FormField>
            </div>
            <FormField
              label={d.members.phone}
              htmlFor={phoneId}
              variant="auth"
              error={fe?.phone}
            >
              <PhoneInput
                id={phoneId}
                name="phone"
                locale={locale}
                variant="auth"
                countryLabel={d.registerUser.countryCode}
                placeholder={d.registerUser.phonePlaceholder}
                value={phone}
                onChange={setPhone}
              />
            </FormField>
            <div className="grid gap-4 sm:grid-cols-2">
              <FormField
                label={d.members.selectPlan}
                htmlFor={planId}
                variant="auth"
                error={fe?.plan_id}
              >
                <Select
                  id={planId}
                  required
                  name="plan_id"
                  variant="auth"
                  value={selectedPlan}
                  onChange={(e) => setSelectedPlan(e.target.value)}
                >
                  {plans.map((p) => (
                    <option key={p.id} value={p.id}>
                      {formatPlanLabel(p, d.registerUser.planPrice)}
                    </option>
                  ))}
                </Select>
              </FormField>
              <FormField
                label={d.members.paymentMethod}
                htmlFor={methodId}
                variant="auth"
                error={fe?.method}
              >
                <Select
                  id={methodId}
                  name="method"
                  variant="auth"
                  value={method}
                  onChange={(e) =>
                    setMethod(e.target.value as "cash" | "transfer")
                  }
                >
                  <option value="cash">{d.members.cash}</option>
                  <option value="transfer">{d.members.transfer}</option>
                </Select>
              </FormField>
            </div>
            {errorBanner}
            {emailWarning}
            {actions}
          </form>
        )
      ) : (
        <form action={teamAction} className="flex flex-col gap-4" noValidate>
          <input type="hidden" name="locale" value={locale} />
          <input type="hidden" name="role" value={role} />
          <div className="grid gap-4 sm:grid-cols-2">
            <FormField
              label={d.members.name}
              htmlFor={nameId}
              variant="auth"
              error={fe?.name}
            >
              <Input
                id={nameId}
                required
                name="name"
                variant="auth"
                maxLength={LIMITS.personName}
                autoComplete="name"
                placeholder={d.registerUser.namePlaceholder}
                value={name}
                onChange={(e) => setName(sanitizePersonNameInput(e.target.value))}
              />
            </FormField>
            <FormField
              label={d.registerUser.email}
              htmlFor={emailId}
              variant="auth"
              error={fe?.email}
            >
              <Input
                id={emailId}
                required
                type="email"
                name="email"
                variant="auth"
                maxLength={LIMITS.email}
                autoComplete="email"
                autoCapitalize="none"
                autoCorrect="off"
                spellCheck={false}
                inputMode="email"
                placeholder={d.registerUser.emailPlaceholder}
                value={email}
                onChange={(e) => setEmail(sanitizeEmailInput(e.target.value))}
              />
            </FormField>
          </div>
          <FormField
            label={d.members.phone}
            htmlFor={phoneId}
            variant="auth"
            error={fe?.phone}
          >
            <PhoneInput
              id={phoneId}
              name="phone"
              locale={locale}
              variant="auth"
              countryLabel={d.registerUser.countryCode}
              placeholder={d.registerUser.phonePlaceholder}
              value={phone}
              onChange={setPhone}
            />
          </FormField>
          {errorBanner}
          {emailWarning}
          {actions}
        </form>
      )}
    </div>
  );
}

export function RegisterUserDialog({
  locale,
  open,
  onOpenChange,
  defaultRole = "member",
  allowedRoles,
  canManageMembers,
  canManageStaff,
  plans = [],
  onSuccess,
}: RegisterUserDialogProps) {
  const d = getDictionary(locale);
  const roles = rolesForPermissions(
    canManageMembers,
    canManageStaff,
    allowedRoles,
  );
  const initialRole =
    roles.includes(defaultRole) ? defaultRole : (roles[0] ?? "member");
  const [session, setSession] = useState(0);
  const [wasOpen, setWasOpen] = useState(open);
  if (open !== wasOpen) {
    setWasOpen(open);
    if (open) setSession((n) => n + 1);
  }

  return (
    <Dialog
      open={open}
      onOpenChange={onOpenChange}
      title={d.registerUser.title}
      description={d.registerUser.description}
      closeLabel={d.registerUser.close}
      className="max-w-xl sm:max-w-2xl"
    >
      {roles.length === 0 ? (
        <p className="text-sm text-[var(--color-muted)]">{d.common.forbidden}</p>
      ) : open ? (
        <RegisterUserFormBody
          key={session}
          locale={locale}
          roles={roles}
          initialRole={initialRole}
          plans={plans}
          onOpenChange={onOpenChange}
          onSuccess={onSuccess}
        />
      ) : null}
    </Dialog>
  );
}

type RegisterUserButtonProps = {
  locale: Locale;
  canManageMembers: boolean;
  canManageStaff: boolean;
  plans?: RegisterPlanOption[];
  defaultRole?: RegisterRole;
  allowedRoles?: RegisterRole[];
  label?: string;
  className?: string;
  /** Default is primary filled; quickAction matches dashboard chips */
  appearance?: "primary" | "quickAction";
  icon?: ReactNode;
  onSuccess?: (payload: RegisterSuccessPayload) => void;
};

export function RegisterUserButton({
  locale,
  canManageMembers,
  canManageStaff,
  plans = [],
  defaultRole,
  allowedRoles,
  label,
  className = "",
  appearance = "primary",
  icon,
  onSuccess,
}: RegisterUserButtonProps) {
  const d = getDictionary(locale);
  const [open, setOpen] = useState(false);
  const roles = rolesForPermissions(
    canManageMembers,
    canManageStaff,
    allowedRoles,
  );
  if (roles.length === 0) return null;

  const triggerClass =
    appearance === "quickAction"
      ? `inline-flex w-full items-center justify-center gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3.5 py-2.5 text-sm font-semibold text-[var(--color-text)] shadow-sm transition-colors hover:border-[var(--color-primary)]/40 hover:bg-[var(--color-surface-hover)] ${className}`.trim()
      : `inline-flex shrink-0 items-center gap-1.5 px-3.5 py-2 shadow-sm transition-[background-color,box-shadow,transform,filter] duration-200 hover:brightness-[0.92] hover:shadow-md active:translate-y-px active:brightness-[0.88] active:shadow-sm ${className}`.trim();

  return (
    <>
      {appearance === "quickAction" ? (
        <button type="button" className={triggerClass} onClick={() => setOpen(true)}>
          {icon ?? <Plus className="h-4 w-4" aria-hidden />}
          {label ?? d.registerUser.open}
        </button>
      ) : (
        <Button
          type="button"
          variant="primary"
          className={triggerClass}
          onClick={() => setOpen(true)}
        >
          {icon ?? <Plus className="h-4 w-4" aria-hidden />}
          {label ?? d.registerUser.open}
        </Button>
      )}
      <RegisterUserDialog
        locale={locale}
        open={open}
        onOpenChange={setOpen}
        defaultRole={defaultRole}
        allowedRoles={allowedRoles}
        canManageMembers={canManageMembers}
        canManageStaff={canManageStaff}
        plans={plans}
        onSuccess={onSuccess}
      />
    </>
  );
}

// src/lib/components/register/RegisterUserDialog.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { goto } from '$app/navigation';
	import Dumbbell from '@lucide/svelte/icons/dumbbell';
	import UserRound from '@lucide/svelte/icons/user-round';
	import Users from '@lucide/svelte/icons/users';
	import Button from '$lib/components/ui/Button.svelte';
	import Dialog from '$lib/components/ui/Dialog.svelte';
	import FormField from '$lib/components/ui/FormField.svelte';
	import Input from '$lib/components/ui/Input.svelte';
	import Select from '$lib/components/ui/Select.svelte';
	import type { Locale } from '$lib/i18n/config';
	import { getDictionary } from '$lib/i18n/dictionaries';
	import type { CreateMemberState } from '$lib/server/members/actions';
	import type { CreateTeamMemberState } from '$lib/server/team/actions';
	import {
		LIMITS,
		sanitizeEmailInput,
		sanitizePersonNameInput,
		sanitizePhoneInput
	} from '$lib/validation/schemas';

	export type RegisterRole = 'member' | 'trainer' | 'staff';

	export type RegisterPlanOption = {
		id: string;
		name: string;
		price: number;
		duration_days: number;
	};

	export type RegisterSuccessPayload = {
		memberId?: string;
		teamMemberId?: string;
		role: RegisterRole;
	};

	type Props = {
		locale: Locale;
		open: boolean;
		onOpenChange: (open: boolean) => void;
		defaultRole?: RegisterRole;
		allowedRoles?: RegisterRole[];
		canManageMembers: boolean;
		canManageStaff: boolean;
		plans?: RegisterPlanOption[];
		/** Form action for member create (default dashboard). */
		memberAction?: string;
		/** Form action for trainer/staff create. */
		teamAction?: string;
		onSuccess?: (payload: RegisterSuccessPayload) => void;
	};

	let {
		locale,
		open,
		onOpenChange,
		defaultRole = 'member',
		allowedRoles = undefined,
		canManageMembers,
		canManageStaff,
		plans = [],
		memberAction = '?/createMember',
		teamAction = '?/createTeam',
		onSuccess
	}: Props = $props();

	const d = $derived(getDictionary(locale));

	function rolesForPermissions(): RegisterRole[] {
		const base: RegisterRole[] = [];
		if (canManageMembers) base.push('member');
		if (canManageStaff) {
			base.push('trainer', 'staff');
		}
		if (!allowedRoles) return base;
		return base.filter((r) => allowedRoles.includes(r));
	}

	const roles = $derived(rolesForPermissions());
	const initialRole = $derived(
		roles.includes(defaultRole) ? defaultRole : (roles[0] ?? 'member')
	);

	let session = $state(0);
	let wasOpen = $state(false);
	let role = $state<RegisterRole>('member');
	let name = $state('');
	let phone = $state('');
	let email = $state('');
	let selectedPlan = $state('');
	let method = $state<'cash' | 'transfer'>('cash');
	let pending = $state(false);
	let formError = $state<string | undefined>(undefined);
	let fieldErrors = $state<Record<string, string> | undefined>(undefined);
	let emailWarning = $state<string | undefined>(undefined);

	$effect(() => {
		if (open && !wasOpen) {
			session += 1;
			role = initialRole;
			resetFields();
		}
		wasOpen = open;
	});

	const isMember = $derived(role === 'member');
	const canSubmit = $derived(
		isMember
			? name.trim().length > 0 &&
					email.trim().length > 0 &&
					selectedPlan.length > 0 &&
					plans.length > 0 &&
					!pending
			: name.trim().length > 0 && email.trim().length > 0 && !pending
	);

	function resetFields() {
		name = '';
		phone = '';
		email = '';
		selectedPlan = plans[0]?.id ?? '';
		method = 'cash';
		pending = false;
		formError = undefined;
		fieldErrors = undefined;
		emailWarning = undefined;
	}

	function roleLabel(r: RegisterRole) {
		if (r === 'member') return d.registerUser.roleMember;
		if (r === 'trainer') return d.registerUser.roleTrainer;
		return d.registerUser.roleStaff;
	}

	function formatPlanLabel(plan: RegisterPlanOption) {
		const price = typeof plan.price === 'number' ? plan.price.toFixed(2) : String(plan.price);
		const meta = d.registerUser.planPrice
			.replace('{days}', String(plan.duration_days))
			.replace('{price}', price);
		return `${plan.name} — ${meta}`;
	}

	function handleMemberResult(data: CreateMemberState) {
		if (!data) return;
		if (data.fieldErrors) fieldErrors = data.fieldErrors;
		if (data.error) formError = data.error;
		if (data.emailWarning) emailWarning = data.emailWarning;
		if (data.success) {
			onSuccess?.({ role: 'member', memberId: data.memberId });
			onOpenChange(false);
			if (data.memberId) {
				void goto(`/${locale}/members/${data.memberId}`);
			}
		}
	}

	function handleTeamResult(data: CreateTeamMemberState) {
		if (!data) return;
		if (data.fieldErrors) fieldErrors = data.fieldErrors;
		if (data.error) formError = data.error;
		if (data.emailWarning) emailWarning = data.emailWarning;
		if (data.success) {
			const r = (data.role ?? role) as RegisterRole;
			onSuccess?.({ role: r, teamMemberId: data.teamMemberId });
			onOpenChange(false);
			if (data.teamMemberId) {
				const path = r === 'trainer' ? 'trainers' : 'staff';
				void goto(`/${locale}/${path}/${data.teamMemberId}`);
			}
		}
	}
</script>

<Dialog
	{open}
	{onOpenChange}
	title={d.registerUser.title}
	description={d.registerUser.description}
	closeLabel={d.registerUser.close}
	class="max-w-xl sm:max-w-2xl"
>
	{#if roles.length === 0}
		<p class="text-sm text-[var(--color-muted)]">{d.common.forbidden}</p>
	{:else if open}
		{#key session}
			<div class="flex flex-col gap-5">
				<fieldset>
					<legend class="mb-2 text-sm font-medium text-[var(--color-text)]">
						{d.registerUser.roleLabel}
					</legend>
					<div
						role="radiogroup"
						aria-label={d.registerUser.roleLabel}
						class="grid gap-1 rounded-xl bg-[var(--color-surface-hover)] p-1 {roles.length === 1
							? 'grid-cols-1'
							: roles.length === 2
								? 'grid-cols-2'
								: 'grid-cols-3'}"
					>
						{#each roles as r (r)}
							{@const selected = role === r}
							<label
								class="flex cursor-pointer flex-col items-center gap-1 rounded-lg px-2 py-2.5 text-center text-xs font-semibold transition-all sm:text-sm {selected
									? 'bg-[var(--color-surface)] text-[var(--color-text)] shadow-sm ring-1 ring-[var(--color-border)]'
									: 'text-[var(--color-muted)] hover:text-[var(--color-text)]'}"
							>
								<input
									type="radio"
									name="register-role"
									value={r}
									checked={selected}
									onchange={() => {
										role = r;
										formError = undefined;
										fieldErrors = undefined;
										emailWarning = undefined;
									}}
									class="sr-only"
								/>
								{#if r === 'member'}
									<UserRound
										class="h-4 w-4 {selected
											? 'text-[var(--color-primary)]'
											: 'text-[var(--color-muted)]'}"
										aria-hidden="true"
									/>
								{:else if r === 'trainer'}
									<Dumbbell
										class="h-4 w-4 {selected
											? 'text-[var(--color-primary)]'
											: 'text-[var(--color-muted)]'}"
										aria-hidden="true"
									/>
								{:else}
									<Users
										class="h-4 w-4 {selected
											? 'text-[var(--color-primary)]'
											: 'text-[var(--color-muted)]'}"
										aria-hidden="true"
									/>
								{/if}
								{roleLabel(r)}
							</label>
						{/each}
					</div>
				</fieldset>

				{#if isMember}
					{#if plans.length === 0}
						<div class="flex flex-col gap-4">
							<p
								class="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-hover)] p-3 text-sm text-[var(--color-muted)]"
								role="status"
							>
								{d.registerUser.noPlans}
							</p>
							<button
								type="button"
								onclick={() => onOpenChange(false)}
								class="text-center text-sm text-[var(--color-muted)] transition-colors hover:text-[var(--color-text)]"
							>
								{d.registerUser.cancel}
							</button>
						</div>
					{:else}
						<form
							method="POST"
							action={memberAction}
							class="flex flex-col gap-4"
							novalidate
							use:enhance={() => {
								pending = true;
								formError = undefined;
								fieldErrors = undefined;
								emailWarning = undefined;
								return async ({ result }) => {
									pending = false;
									if (result.type === 'success' || result.type === 'failure') {
										handleMemberResult(result.data as CreateMemberState);
									}
								};
							}}
						>
							<input type="hidden" name="locale" value={locale} />
							<div class="grid gap-4 sm:grid-cols-2">
								<FormField label={d.members.name} htmlFor="reg-name" error={fieldErrors?.name}>
									{#snippet children({ invalid, describedBy })}
										<Input
											id="reg-name"
											required
											name="name"
											maxlength={LIMITS.personName}
											autocomplete="name"
											placeholder={d.registerUser.namePlaceholder}
											bind:value={name}
											oninput={(e) => {
												name = sanitizePersonNameInput((e.target as HTMLInputElement).value);
											}}
											{invalid}
											{describedBy}
										/>
									{/snippet}
								</FormField>
								<FormField
									label={d.registerUser.email}
									htmlFor="reg-email"
									error={fieldErrors?.email}
								>
									{#snippet children({ invalid, describedBy })}
										<Input
											id="reg-email"
											required
											type="email"
											name="email"
											maxlength={LIMITS.email}
											autocomplete="email"
											inputmode="email"
											spellcheck={false}
											placeholder={d.registerUser.emailPlaceholder}
											bind:value={email}
											oninput={(e) => {
												email = sanitizeEmailInput((e.target as HTMLInputElement).value);
											}}
											{invalid}
											{describedBy}
										/>
									{/snippet}
								</FormField>
							</div>
							<FormField label={d.members.phone} htmlFor="reg-phone" error={fieldErrors?.phone}>
								{#snippet children({ invalid, describedBy })}
									<Input
										id="reg-phone"
										name="phone"
										placeholder={d.registerUser.phonePlaceholder}
										bind:value={phone}
										oninput={(e) => {
											phone = sanitizePhoneInput((e.target as HTMLInputElement).value);
										}}
										{invalid}
										{describedBy}
									/>
								{/snippet}
							</FormField>
							<div class="grid gap-4 sm:grid-cols-2">
								<FormField
									label={d.members.selectPlan}
									htmlFor="reg-plan"
									error={fieldErrors?.plan_id}
								>
									{#snippet children({ invalid, describedBy })}
										<Select
											id="reg-plan"
											required
											name="plan_id"
											bind:value={selectedPlan}
											{invalid}
											{describedBy}
										>
											{#each plans as p (p.id)}
												<option value={p.id}>{formatPlanLabel(p)}</option>
											{/each}
										</Select>
									{/snippet}
								</FormField>
								<FormField
									label={d.members.paymentMethod}
									htmlFor="reg-method"
									error={fieldErrors?.method}
								>
									{#snippet children({ invalid, describedBy })}
										<Select id="reg-method" name="method" bind:value={method} {invalid} {describedBy}>
											<option value="cash">{d.members.cash}</option>
											<option value="transfer">{d.members.transfer}</option>
										</Select>
									{/snippet}
								</FormField>
							</div>
							{#if formError}
								<p
									class="rounded-lg border border-[var(--color-primary)]/20 bg-[var(--color-primary)]/10 p-3 text-sm font-medium text-[var(--color-primary)]"
									role="alert"
								>
									{formError}
								</p>
							{/if}
							{#if emailWarning}
								<p
									class="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-hover)] p-3 text-sm text-[var(--color-muted)]"
									role="status"
								>
									{emailWarning}
								</p>
							{/if}
							<div class="flex flex-row-reverse flex-wrap items-center gap-3 pt-1">
								<Button type="submit" class="min-w-[8.5rem] flex-1 sm:flex-none" disabled={!canSubmit}>
									{pending ? d.registerUser.submitting : d.registerUser.submit}
								</Button>
								<Button
									type="button"
									variant="ghost"
									class="min-w-[6rem] flex-1 px-4 py-2.5 sm:flex-none"
									onclick={() => onOpenChange(false)}
								>
									{d.registerUser.cancel}
								</Button>
							</div>
						</form>
					{/if}
				{:else}
					<form
						method="POST"
						action={teamAction}
						class="flex flex-col gap-4"
						novalidate
						use:enhance={() => {
							pending = true;
							formError = undefined;
							fieldErrors = undefined;
							emailWarning = undefined;
							return async ({ result }) => {
								pending = false;
								if (result.type === 'success' || result.type === 'failure') {
									handleTeamResult(result.data as CreateTeamMemberState);
								}
							};
						}}
					>
						<input type="hidden" name="locale" value={locale} />
						<input type="hidden" name="role" value={role} />
						<div class="grid gap-4 sm:grid-cols-2">
							<FormField label={d.members.name} htmlFor="reg-team-name" error={fieldErrors?.name}>
								{#snippet children({ invalid, describedBy })}
									<Input
										id="reg-team-name"
										required
										name="name"
										maxlength={LIMITS.personName}
										autocomplete="name"
										placeholder={d.registerUser.namePlaceholder}
										bind:value={name}
										oninput={(e) => {
											name = sanitizePersonNameInput((e.target as HTMLInputElement).value);
										}}
										{invalid}
										{describedBy}
									/>
								{/snippet}
							</FormField>
							<FormField
								label={d.registerUser.email}
								htmlFor="reg-team-email"
								error={fieldErrors?.email}
							>
								{#snippet children({ invalid, describedBy })}
									<Input
										id="reg-team-email"
										required
										type="email"
										name="email"
										maxlength={LIMITS.email}
										autocomplete="email"
										inputmode="email"
										spellcheck={false}
										placeholder={d.registerUser.emailPlaceholder}
										bind:value={email}
										oninput={(e) => {
											email = sanitizeEmailInput((e.target as HTMLInputElement).value);
										}}
										{invalid}
										{describedBy}
									/>
								{/snippet}
							</FormField>
						</div>
						<FormField label={d.members.phone} htmlFor="reg-team-phone" error={fieldErrors?.phone}>
							{#snippet children({ invalid, describedBy })}
								<Input
									id="reg-team-phone"
									name="phone"
									placeholder={d.registerUser.phonePlaceholder}
									bind:value={phone}
									oninput={(e) => {
										phone = sanitizePhoneInput((e.target as HTMLInputElement).value);
									}}
									{invalid}
									{describedBy}
								/>
							{/snippet}
						</FormField>
						{#if formError}
							<p
								class="rounded-lg border border-[var(--color-primary)]/20 bg-[var(--color-primary)]/10 p-3 text-sm font-medium text-[var(--color-primary)]"
								role="alert"
							>
								{formError}
							</p>
						{/if}
						{#if emailWarning}
							<p
								class="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-hover)] p-3 text-sm text-[var(--color-muted)]"
								role="status"
							>
								{emailWarning}
							</p>
						{/if}
						<div class="flex flex-row-reverse flex-wrap items-center gap-3 pt-1">
							<Button type="submit" class="min-w-[8.5rem] flex-1 sm:flex-none" disabled={!canSubmit}>
								{pending ? d.registerUser.submitting : d.registerUser.submit}
							</Button>
							<Button
								type="button"
								variant="ghost"
								class="min-w-[6rem] flex-1 px-4 py-2.5 sm:flex-none"
								onclick={() => onOpenChange(false)}
							>
								{d.registerUser.cancel}
							</Button>
						</div>
					</form>
				{/if}
			</div>
		{/key}
	{/if}
</Dialog>
